### ISSUE TITLE
Wm320 board reading?

### ISSUE THREAD

**Issue by Weanuts** [o-gs/dji-firmware-tools#102]
Might someone please help with this reading? What has happened in putty? Trying to boot Nand. ![read board1](https://user-images.githubusercontent.com/16791902/50111263-43568300-01f1-11e9-8522-8c09e7aea3b7.PNG)

**Comment by mefistotelis** [comment]
If that's a serial interface which should display text, then either transmission parameters are wrong or your usb-to-ttl is incompatible.

**Comment by Weanuts** [comment]
Do not know if following proper protocol, but here goes. Was able to connect changing baud rate. I received boot me boot me """""""""" Using same setup was not able to receive any info off of nand chip after disconnect of 3.3v and BT00 and BT01. Can you please help with link to download TI utilities and u boot images. I have read your posts on (Flashing firmware on DaVinci media processors · mefistotelis/phantom-firmware-tools Wiki · GitHub), and https://phantompilots.com/threads/fixing-flash-in-dm365-chip-within-ph3-pro-gimbal.127310/  I am at a loss after these readings.

I must say that you a genius when I read  a few of your hundreds, probably thousands of posts.

thank you for help

**Comment by Weanuts** [comment]
Can you recommend which Nand flash chip is needed on my board?   4YE12 NQ283 (MT29F2G08ABAEAH4)  or 4UF12 NW361  (MT29F1G08ABAEAH4)  My board is a P01069.07

thank you again

**Comment by mefistotelis** [comment]
> which Nand flash chip is needed on my board?

Look at board pictures, and check which of them is missing on Ph3 Advanced board - DM36x only exists in Pro.

> Can you please help with link to download TI utilities and u boot images.

TI utilities are on TI site, which is linked to here:
https://github.com/o-gs/dji-firmware-tools/wiki/Flashing-firmware-on-DaVinci-media-processors

Modules from P3X firmware - you can just extract from official firmware releases. Here is a tool for downloading firmwares:
https://github.com/cs2000/DankDroneDownloader
Start the extraction with `dji_xv4_fwcon.py`, then read wiki to figure out what to do next.

**Comment by Weanuts** [comment]
I am a but head. I did not see the third choice, My craft is a DJI phantom 3 professional.  My board is a P01069.07  I believe I need a MXIC X154009 MX30LF2G18AC-XKI 8C149000 

(63-ball 11x9 VFBGA | 3V SLC 2GBit NAND Flash memory; contains programming for Ambarella A9
-- | --)


I am missing on screen play. (fpv) 08 00 15 00 device not detected. 
Could you please tell me if I am correct, this time?

thanks again John

**Comment by mefistotelis** [comment]
Ambarella writes on SD-card and forwads FPV signal to DaVinci. If SD-card write works fine, then Ambarella works correctly. So - no, what you wrote is not correct.

**Comment by Weanuts** [comment]
SD-card receives and is written to, movies and stills that can be seen on my computer. So in short, what am I lacking (other than experience) to achieve an on screen picture on my Ipad?

thank you once again for taking the time to instruct me

**Comment by Weanuts** [comment]
Correct, m0800 is upset. How do I know if Loading kernel via USB stick is possible, on my board? If so, can I use a  USB 2.0 Type A Female To Micro B Male Adapter to load kerne (?)l onto Wm320 board via usb stick?

I again much appreciate your help with my endeavor.

Seasons greetings,
 John

**Comment by mefistotelis** [comment]
> How do I know if Loading kernel via USB stick is possible, on my board?

Try it and you'll know.

> can I use a USB 2.0 Type A Female To Micro B Male Adapter to load kerne (?)l onto Wm320 board via usb stick?

So to simplify - you want to ask whether you can use micro-USB port soldered on the top board.
The answer is - you probably can, but not in the way you think; that port is connected to an USB Switch which can be switched to DaVinci. But normally, it is switched to Ambarella.

If you can figure out how to toggle the switch, then you should be able to use that USB port. I never tried that.

**Comment by Weanuts** [comment]
Thank you for answer. The power was out here yesterday for 12 hours so I was late getting back to you. I will solder to board and update you. 

thank you again
John

**Comment by Weanuts** [comment]
Ok, I have everything ready,  pin 1 and 2 from ofdm to female usb connecter, but, for life of me, I cannot find ("After the pad is connected, use TI utilities on connected PC to flash your new image:") TI utilities ???? I found TI connect, but!

**Comment by mefistotelis** [comment]
It was explained two paragraphs later; I made it more connected and better explained now.

**Comment by Weanuts** [comment]
![capture2](https://user-images.githubusercontent.com/16791902/50731059-9183e580-1110-11e9-965e-8e22fbfcbe49.PNG)
Well after a lot more reading, I finally started to re flash but, I am back at a stalemate. I tried numerous  times to re flash but I get the results as the enclosed  capture. Can I continue with different flash or do I need a new chip?

**Comment by mefistotelis** [comment]
The message says interfacing error, not NAND write error.

Make sure DaVinci gets enough power.

**Comment by Weanuts** [comment]
Can I use an auxiliary power source to supply 5v power to board?

thank you

**Comment by mefistotelis** [comment]
That is exactly what I suggested.

**Comment by priegor** [comment]
"File ubl1.img is not present"

**Comment by Weanuts** [comment]
mefistotelis, I was able to write to nand but not sure if I am "done" or just starting. Here is a printout of the operation.
Your help is extremely appreciated.
[Success or.txt](https://github.com/o-gs/dji-firmware-tools/files/2731247/Success.or.txt)

**Comment by mefistotelis** [comment]
Looks ok to me. Remove the BOOT0 wire and check what serial interface shows during boot.

**Comment by priegor** [comment]
If you power on board without OFDM module and Gimbal, log seems ok. Now need fix 8fps issue.
Follow this [post](https://phantompilots.com/threads/fixing-flash-in-dm365-chip-within-ph3-pro-gimbal.127310/#post-1301798)
Read "UPDATE - Regarding 8 FPS FPV after NAND replace:"

**Comment by mefistotelis** [comment]
This issue is described on the wiki:

<pre>Loading from nand0, offset 0x4a0000
** Unknown image type
Wrong Image Format for bootm command
ERROR: can't get kernel image!</pre>

Beyond kernel - the Linux seem to be booting ok, so that's the last thing you need to fix.

**Comment by Weanuts** [comment]
So can I, try this??

Home/DJI Firmwares/Firmware m0800/


"Flashing firmware via SD card",

"By official package in camera" ??

**Comment by mefistotelis** [comment]
Hm, I was always flashing the kernel "by hand" (I mean, using YModem and then `dd`), and I referred to this wiki:
https://github.com/o-gs/dji-firmware-tools/wiki/Flashing-firmware-on-DaVinci-media-processors

But what you suggest might actually work. The DaVinci Linux is booting, so it should be able to perform the update correctly.

Try it. Either with whole package, or only the module 0800 in camera.
I'm pretty sure it will work.

**Comment by Weanuts** [comment]
SUCCESS:

Ok I tried it with the whole package. It worked. I have video transmission to my Ipad.
[P3X_FW_LOG_AB.txt](https://github.com/o-gs/dji-firmware-tools/files/2735123/P3X_FW_LOG_AB.txt)
[P3X_FW_RESULT_AB.txt](https://github.com/o-gs/dji-firmware-tools/files/2735125/P3X_FW_RESULT_AB.txt)

1/ Can you tell me from files if I have to change frame rate? (8fps or greater>)
2/ Your write up on leaving craft for a long period of time without usage, could this have caused my problem of "No video transmission",
3/ or excessive heat caused by upgrades or downgrades.

This craft came to me broken up internally. It had 4 battery charges at the time. It now has 27 recharges, and I have flown it a maximum of 30 minutes. The remainder of the recharges were consumed by trying repair the software. 
 

I must say that for YOUR help and others on this forum and the large amount of info found on the web I will forever indebted.

thank you
mefistotelis

**Comment by mefistotelis** [comment]
>  1/ Can you tell me from files if I have to change frame rate? (8fps or greater>)

If you see video normally, then you don't have the issue. Get the drone to a well lit location and wave your hand in front of it to check.

> 2/ Your write up on leaving craft for a long period of time without usage, could this have caused my problem of "No video transmission",

Yes.

> 3/ or excessive heat caused by upgrades or downgrades.

Yes, that could also be the cause.

**Comment by Weanuts** [comment]
I want t thank you again for all your help. I still have to break down the unit to work on the Wm320 board, to remove remaining jumpers and install new heat absorbing pads, before I go for my first real flight.
Have a great one.
