### ISSUE TITLE
Error: No response on calibration command Jointcoarse request

### ISSUE THREAD

**Issue by Petar92spark** [o-gs/dji-firmware-tools#104]
Hey guys, 
I am tring to do a gimbal calibration on spark,
but I am getting this error.

Tried to do the same on another,working drone, same thing...
anyone have a possible solution?
Thanks!

**Comment by mefistotelis** [comment]
A solution would be to fix your connection, or use the tool properly - depending on what you really did.
You may try to make Dji Assistant work, or use comm_serialtalk.py as simpler too,l to debug the connection. There is currently no tool which would try to help with making the connection.
