### ISSUE TITLE
Help! Can I use P3 Pro Gimbal in P3 4k?

### ISSUE THREAD

**Issue by Spider84** [o-gs/dji-firmware-tools#122]
Hello!

My P3 4k gimbal is deaded after crash. I can't find true P3 4k gimbal. But I have many P3 Pro gimbals. Can I use them?
I have readed that I can resolder resistor to switch USB direction. Where I can read what exactly? 

Thx.

**Comment by Spider84** [comment]
Gimbal is different.  Connector is different :(
![IMG_20190512_215614](https://user-images.githubusercontent.com/1863325/57584859-f9ed3400-7501-11e9-912f-13f8c9b95801.jpg)
![IMG_20190512_215647](https://user-images.githubusercontent.com/1863325/57584860-f9ed3400-7501-11e9-9d59-c5f3cf10e900.jpg)

**Comment by mefistotelis** [comment]
Yup. Phantom 3 Pro and Advanced are very similar and the boards can be switched between them. Other models, like Phantom 3 4K and Phantom 3 Standard are different, don't know if compatible in their own group.

The photos show Phantom 3 Advanced board.

**Comment by Spider84** [comment]
> The photos show Phantom 3 Advanced board.
No. At photo P3 4k board

**Comment by mefistotelis** [comment]
OK, that is interesting. I didn't knew 4k board looks like Advanced..

So you're saying those are still not compatible? where?

**Comment by Spider84** [comment]
First: This board has different 12V connector. If I connect P3 Pro gimbal to P3 4k drone - drone don't turn on. Short circuit issue :( 
Second: At pictures below you can see that PCB is different then Pro/Adv.
Around 2 capacitors different polygon.
Different polygon around connector and different pinout as result.
Additional Transistors (??? SOT-23) near SD Card slot.
Third: Another Camera PCB, but I lost my cam (did broke gimbal and lost Cam on fly...)
![IMG_20190512_232141](https://user-images.githubusercontent.com/1863325/57585666-f90dcf80-750c-11e9-82b6-a0ab0393a1e8.jpg)
![IMG_20190512_232047](https://user-images.githubusercontent.com/1863325/57585667-f90dcf80-750c-11e9-8e3d-8c6ebb204118.jpg)
![IMG_20190512_232131](https://user-images.githubusercontent.com/1863325/57585668-f9a66600-750c-11e9-806f-e3334a6208ca.jpg)
![photo_2019-05-12_23-29-03](https://user-images.githubusercontent.com/1863325/57585724-d16b3700-750d-11e9-9859-555c8e58a1ff.jpg)

**Comment by Spider84** [comment]
Camera from P3 Pro don't work with P3 4K Gimbal - as result in DJI GO Gimbal not detected, and no picture.
BUT! Camera from P3 4K Work on P3 Pro gimbal (in my search of camera I found this example of replacement)

P.S. I'm searching for P3 4K camera :((( Please!

**Comment by Spider84** [comment]
I finally resolve problem.
In P3 4k used camera from P3 Adv.
Now All work fine.
