### ISSUE TITLE
8fps Phantom 3 pro gimbal board

### ISSUE THREAD

**Issue by rishanavinash11** [o-gs/dji-firmware-tools#146]
I flashed some Phantom 3 pro gimbal boards with success but i got now 2 of them with the 8fps problem.

I was reading in the article again and saw that i have to use the dmxx_encode_usb......

When i started i got the following error in cmd:

C:\Users\risha\Desktop\DJI\dji-firmware-tools-master>dm3xx_encode_usb_hardcoder.py
Traceback (most recent call last):
  File "C:\Users\risha\Desktop\DJI\dji-firmware-tools-master\dm3xx_encode_usb_hardcoder.py", line 71, in <module>
    from capstone import *
ModuleNotFoundError: No module named 'capstone'

Does anyone know how to fix this?

**Comment by mefistotelis** [comment]
module not found -> install module?

make sure you install correct one, you want the capstone disassembly engine. multiple things use that name.
