### ISSUE TITLE
 Phantom 4 Pro gimbal calibration

### ISSUE THREAD

**Issue by nonsolodroni** [o-gs/dji-firmware-tools#147]
Hello,
I have a problem with a Gimbal P4 Pro. When the drone rotates on itself, roll and Pitch slowly swing, losing the horizon.
There is a solution?
Thanks so much.

**Comment by robxs1** [comment]
Possible ,1 gimbal esc or  2. gimbal imu

**Comment by mefistotelis** [comment]
Duplicate of:
https://github.com/o-gs/dji-firmware-tools/issues/99
