### ISSUE TITLE
Lightbridge and OcuSync protocol description

### ISSUE THREAD

**Issue by kostaov** [o-gs/dji-firmware-tools#148]
Hi,
I need a protocol description similar to MAVLink (https://arxiv.org/pdf/1906.10641.pdf) for DJI Lightbridge 1,2; OcuSync 1,2,3 only.
This description should contain the frame structure and a description of all types of transmitted messages and their fields.

Can you help me?

**Comment by mefistotelis** [comment]
Why are you asking us? Isn't DJI the owner of such spec?
We are not an unpaid branch of DJI support.

Though if we would be that, we'd probably direct you to DJI Onboard SDK.

Anyway, this project has a wiki - you should start with that. Then you may want to describe your findings, give something back to the community. Then it's a proper time for asking more in-depth questions.

If you choose to go that way, you may also join the Slack community. Invite is in a project owned by @Bin4ry here on Github, easy to find.
