### ISSUE TITLE
Mavic Mini: Response on parameter X indicates end of list

### ISSUE THREAD

**Issue by rohsshor** [o-gs/dji-firmware-tools#151]
Hello Dear,
I'm trying ti read the parameters on mavic mini but on different parameters I obtain this error:
Response on parameter X indicates end of list.

![DJI](https://user-images.githubusercontent.com/35661106/78194503-a834fb80-747d-11ea-9b7b-9aef42c41e39.JPG)

How Can I solve this?
Thank you  
Rohsshor

**Comment by mefistotelis** [comment]
Figure out how these parameters are protected, and how a client can be authorized to access them. By looking into firmware binaries.

**Comment by rohsshor** [comment]
Thank you

**Comment by robxs1** [comment]
@rohsshor have you tried the dji repair tool on the mimi ?

**Comment by rohsshor** [comment]
No Dear, where Can I find it?
