### ISSUE TITLE
GL100 RC Main Board wiki (documentation) mistake: "OcuSync" (Spark)

### ISSUE THREAD

**Issue by pcabreracamara** [o-gs/dji-firmware-tools#152]
Hi all,

I'm reading these days quite a lot the dji-firmware-tools wiki, it's amazing the work you have done.

Regarding the page for the Spark RC board, GL100 [https://github.com/o-gs/dji-firmware-tools/wiki/GL100-Main-board](url), I found a small mistake, probably a Copy/Paste error from the Mavic GL200 RC board:

> It also receives the OcuSync video signal and telemetry from the drone and provides USB interface for reading the data and reconfiguring the drone from a mobile device.

As the Spark drone isn't OcuSync based technology and uses Wifi to communicate with the mobile, should by: 

> It also receives the Enhanced Wifi video signal and telemetry from the drone and provides standard wifi interface for reading the data and reconfiguring the drone from a mobile device.

Don't you agree?

Thank you very much for your ipressive work, I'm looking forward to contributing in the next days.
Pedro

**Comment by mefistotelis** [comment]
Good catch. Though you can connect your mobile via both Wifi and USB. Updating the wiki now.
