### ISSUE TITLE
Package requirements (Crypto.Cypher) on Windows

### ISSUE THREAD

**Issue by jinxy17** [o-gs/dji-firmware-tools#158]
In dji_xv4_fwcon.py: `from Crypto.Cypher import AES`. I've been using **python 3.3 on win10**, fyi.

But it seems impossible to directly install **pycrypto** on Windows with `pip install pycrypto`. Is it okay to download a **pre-compiled** version of pycrypto at [this website](http://www.voidspace.org.uk/python/modules.shtml#pycrypto) that pairs with **python 3.3**? Thanks for reply!

**Comment by mefistotelis** [comment]
Check if you can extract and re-create the package, and whether you get the same data. If you do, the encryption package is ok.
