### ISSUE TITLE
Flashing a single encrypted m0306 module via SD??

### ISSUE THREAD

**Issue by jinxy17** [o-gs/dji-firmware-tools#159]
This might be a bit hard to explain... 

According to this [wiki page](https://github.com/o-gs/dji-firmware-tools/wiki/Firmware-m0306) only several particular versions of m0306 are unencrypted, while all the others (e.g., P3C_FW_V01.09.0200) are encrypted. 
And it is noted under _Flashing - By firmware module in camera_ that flashing the single module (PMCAPPFw3.bin) **"works properly only if the new firmware is unencrypted."** 
Also, in this [wiki page](https://github.com/o-gs/dji-firmware-tools/wiki/Flashing-firmware-via-SD-card#by-firmware-module-in-camera) **"flashing an encrypted firmware this way (by a single firmware module) will cause the updated device to crash during startup"**.

However, I've seen people using `dji_flyc_param_ed.py` to edit m0306 params of encrypted versions (in [this case](https://github.com/digdat0/P3I1_FWProject), P3C_FW_V01.09.0200), and flashing back the single encrypted module (PMCAPPFw3.bin) via SD card.

I wonder how that happen... doesn't it contradict with the notes in the [wiki page](https://github.com/o-gs/dji-firmware-tools/wiki/Firmware-m0306)? Or there is simply some trick that I'm not aware of...?

**Comment by mefistotelis** [comment]
The trick is - `dji_xv4_fwcon.py` decrypts the firmware. You wouldn't be able to find any parameters in encrypted data, would you?
