### ISSUE TITLE
comm_og_service_tool.py

### ISSUE THREAD

**Issue by Maikhonvnc** [o-gs/dji-firmware-tools#163]
I was trying to use this code and I came across this error, which can be 
![Screenshot_1](https://user-images.githubusercontent.com/65917057/82834040-46e64300-9e96-11ea-99f5-272b4cc12300.png)

**Comment by mefistotelis** [comment]
You know there's something called Google, right?
You see error message, first thing you should do is type it into your browser.

**Comment by Maikhonvnc** [comment]
thanks for the help, it's my first time trying to use a code with python but you can see that it won't work
