### ISSUE TITLE
not really an issue sorry. gimbal calibration on mavic air 2?

### ISSUE THREAD

**Issue by 250fpv** [o-gs/dji-firmware-tools#169]
hi,
sorry for posting this in the issues section i couldnt find anywhere else to ask the question. can i use this to calibrate the mavic air 2 gimbal after replacement? and does anyone know if the gimbal needs calibrating on the mavic air 2 after replacement with this like on the mavic air 1 or can i just use the in app calibration once i have replaced the gimbal unit?
thanks
james

**Comment by mingtaoxin** [comment]
Just find free or buy vpn acces to dji servers  and use djo dealer software.. i buy this software on ebay.. it cost about 150$

**Comment by tecdrone** [comment]
> Basta encontrar gratuitamente ou comprar acesso VPN aos servidores dji e usar o software djo dealer .. eu compro este software no ebay .. custou cerca de 150 $

Olá amigo como compra este vpn. Passa o link

**Comment by 954426470** [comment]
I will, you can contact me

**Comment by Saeidhhp** [comment]
> I will, you can contact me

Hello
How can I communicate with you?

**Comment by 954426470** [comment]
What chat software do you have&nbsp;



---Original---
From: ***@***.***&gt;
Date: Sun, Dec 19, 2021 12:03 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [o-gs/dji-firmware-tools] not really an issue sorry. gimbalcalibration on mavic air 2? (#169)




  
I will, you can contact me
  
Hello
 How can I communicate with you?

**Comment by Saeidhhp** [comment]
> What chat software do you have&nbsp;
> 
> 
> 
> ---Original---
> From: ***@***.***&gt;
> Date: Sun, Dec 19, 2021 12:03 PM
> To: ***@***.***&gt;;
> Cc: ***@***.******@***.***&gt;;
> Subject: Re: [o-gs/dji-firmware-tools] not really an issue sorry. gimbalcalibration on mavic air 2? (#169)
> 
> 
> 
> 
>   
> I will, you can contact me
>   
> Hello
>  How can I communicate with you?
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***&gt;

Saeid.hosseinpour01@gmail.com

**Comment by linoko** [comment]
> Just find free or buy vpn acces to dji servers and use djo dealer software.. i buy this software on ebay.. it cost about 150$

Hi , please give link for buying this software

**Comment by mefistotelis** [comment]
No interesting info here, closing.
