### ISSUE TITLE
Phantom 3SE does not update 

### ISSUE THREAD

**Issue by luanpham2014** [o-gs/dji-firmware-tools#179]
Hi everyone. 
My drone FW : P3SE_FW_V01.03.0020 
I try to mod it but when copy file  PMCAPPFw3.bin to sdcard, my drone does not start update. 
I press and hold blind button and keep holding while drone start, but the update not start.
I need a help.
Thank you very much.

**Comment by priegor** [comment]
Hello! Try MCAPPFw.bin

**Comment by luanpham2014** [comment]
> Hello! Try MCAPPFw.bin

Thanks bro. It run the update. 
Do you known mod wifi signal up to 27db ?
