### ISSUE TITLE
got error message "IV must be 16 long" when trying to extract firmware for inspire 1

### ISSUE THREAD

**Issue by psychotik2k3** [o-gs/dji-firmware-tools#185]
Hi i come to use your tool to extract the modules for my inspire 1
when i do this command :
python dji_xv4_fwcon.py -vvv -x -p WM610_V01.11.01.50.bin
it starts to extracts all the modules then when on the 4th module  (FC ) i got this error:
Error: IV must be 16 long

what version of python do i need and pycrypto ?
i have pyhton 2.7 and pycrypto 2.6

i got the same error from version 1.02 while it works with V1.00 firmware

thanks

`WM610_v01.11.01.50.bin: Opening for extraction
WM610_v01.11.01.50.bin: Package format version 2016 detected
WM610_v01.11.01.50.bin: Header:
{   'entry_count': 18,
    'hdrend_offs': 1002,
    'magic': 305419896L,
    'magic_ver': 1,
    'manufacturer': 'DJI',
    'model': 'WM610_FC350Z',
    'padding': '00000000000000000000',
    'timestamp': 1499328594L,
    'ver_latest': 17498262L,
    'ver_latest_enc': 158422432,
    'ver_rollbk': 17498262L,
    'ver_rollbk_enc': 158422432}
WM610_v01.11.01.50.bin: Module index 0
{   'decrypted_len': 62009668L,
    'decrypted_md5': 'e1c16545022bef29c6ab012067403172',
    'dt_offs': 1002L,
    'encrypt_type': 0,
    'reserved2': 1,
    'spcoding': 0,
    'splvalue': 0,
    'stored_len': 62009668L,
    'stored_md5': 'e1c16545022bef29c6ab012067403172',
    'target': 'm0100',
    'target_name': "camera 'Ambarella A9SE' App",
    'version': '02.73.5514'}
WM610_v01.11.01.50.bin: Module index 1
{   'decrypted_len': 420048L,
    'decrypted_md5': '1cdc519e82be535e144cdad3d94e4d0c',
    'dt_offs': 62010670L,
    'encrypt_type': 0,
    'reserved2': 1,
    'spcoding': 0,
    'splvalue': 0,
    'stored_len': 420048L,
    'stored_md5': '1cdc519e82be535e144cdad3d94e4d0c',
    'target': 'm0101',
    'target_name': "camera 'Ambarella A9SE' Ldr",
    'version': '02.73.5514'}
WM610_v01.11.01.50.bin: Module index 2
{   'decrypted_len': 34916L,
    'decrypted_md5': 'd85da1e3804548f16e2b22e9b04a0d8c',
    'dt_offs': 62430718L,
    'encrypt_type': 0,
    'reserved2': 1,
    'spcoding': 0,
    'splvalue': 0,
    'stored_len': 34916L,
    'stored_md5': 'd85da1e3804548f16e2b22e9b04a0d8c',
    'target': 'm0104',
    'target_name': 'camera BCPU',
    'version': '01.08.5460'}
WM610_v01.11.01.50.bin: Module index 3
{   'decrypted_len': 42496L,
    'decrypted_md5': '6fd4ff15e3a78976b5aee33a460cba12',
    'dt_offs': 62465634L,
    'encrypt_type': 1,
    'reserved2': 1,
    'spcoding': 16,
    'splvalue': 0,
    'stored_len': 42496L,
    'stored_md5': '9795e2592dbe4554e809bc3c3b4c8a86',
    'target': 'm0305',
    'target_name': "main controller 'A3' ldr",
    'version': '34.01.0005'}
WM610_v01.11.01.50.bin: Module index 4
{   'decrypted_len': 907008L,
    'decrypted_md5': '58ed83abe8bad1c3061737081b04067c',
    'dt_offs': 62508130L,
    'encrypt_type': 1,
    'reserved2': 1,
    'spcoding': 16,
    'splvalue': 0,
    'stored_len': 907008L,
    'stored_md5': '9f439ed52c4ff5803fcecc2b8c0f723f',
    'target': 'm0306',
    'target_name': "main controller 'A3' app",
    'version': '02.04.5170'}
WM610_v01.11.01.50.bin: Module index 5
{   'decrypted_len': 215616L,
    'decrypted_md5': 'e3992fea38343073fffd7a61bfbe7b57',
    'dt_offs': 63415138L,
    'encrypt_type': 0,
    'reserved2': 1,
    'spcoding': 0,
    'splvalue': 0,
    'stored_len': 215616L,
    'stored_md5': 'e3992fea38343073fffd7a61bfbe7b57',
    'target': 'm0400',
    'target_name': 'gimbal mdl 0',
    'version': '01.30.0303'}
WM610_v01.11.01.50.bin: Module index 6
{   'decrypted_len': 19540L,
    'decrypted_md5': 'c8244c18356014fe4231458846c78bc7',
    'dt_offs': 63630754L,
    'encrypt_type': 0,
    'reserved2': 1,
    'spcoding': 0,
    'splvalue': 0,
    'stored_len': 19540L,
    'stored_md5': 'c8244c18356014fe4231458846c78bc7',
    'target': 'm0401',
    'target_name': 'gimbal model 01',
    'version': '01.04.5906'}
WM610_v01.11.01.50.bin: Module index 7
{   'decrypted_len': 19540L,
    'decrypted_md5': 'c8244c18356014fe4231458846c78bc7',
    'dt_offs': 63650294L,
    'encrypt_type': 0,
    'reserved2': 1,
    'spcoding': 0,
    'splvalue': 0,
    'stored_len': 19540L,
    'stored_md5': 'c8244c18356014fe4231458846c78bc7',
    'target': 'm0402',
    'target_name': 'gimbal model 02',
    'version': '01.04.5906'}
WM610_v01.11.01.50.bin: Module index 8
{   'decrypted_len': 19540L,
    'decrypted_md5': 'c8244c18356014fe4231458846c78bc7',
    'dt_offs': 63669834L,
    'encrypt_type': 0,
    'reserved2': 1,
    'spcoding': 0,
    'splvalue': 0,
    'stored_len': 19540L,
    'stored_md5': 'c8244c18356014fe4231458846c78bc7',
    'target': 'm0403',
    'target_name': 'gimbal model 03',
    'version': '01.04.5906'}
WM610_v01.11.01.50.bin: Module index 9
{   'decrypted_len': 48660L,
    'decrypted_md5': 'e79c5c334da02e282d808587a2181824',
    'dt_offs': 63689374L,
    'encrypt_type': 0,
    'reserved2': 1,
    'spcoding': 0,
    'splvalue': 0,
    'stored_len': 48660L,
    'stored_md5': 'e79c5c334da02e282d808587a2181824',
    'target': 'm0500',
    'target_name': 'central board mdl 0',
    'version': '03.00.1538'}
WM610_v01.11.01.50.bin: Module index 10
{   'decrypted_len': 88420L,
    'decrypted_md5': 'bc227e2f786ad3172f0b3add802f80ca',
    'dt_offs': 63738034L,
    'encrypt_type': 0,
    'reserved2': 1,
    'spcoding': 0,
    'splvalue': 0,
    'stored_len': 88420L,
    'stored_md5': 'bc227e2f786ad3172f0b3add802f80ca',
    'target': 'm0900',
    'target_name': "lightbridge MCU 'STM32F103'",
    'version': '05.00.0000'}
WM610_v01.11.01.50.bin: Module index 11
{   'decrypted_len': 22572L,
    'decrypted_md5': '29ce8442aafc6a26eaebef407b2aea3d',
    'dt_offs': 63826454L,
    'encrypt_type': 0,
    'reserved2': 1,
    'spcoding': 0,
    'splvalue': 0,
    'stored_len': 22572L,
    'stored_md5': '29ce8442aafc6a26eaebef407b2aea3d',
    'target': 'm1100',
    'target_name': 'battery controller 1 app',
    'version': '03.09.0000'}
WM610_v01.11.01.50.bin: Module index 12
{   'decrypted_len': 42496L,
    'decrypted_md5': '108b07f5fa7d52a9781a905de97b7897',
    'dt_offs': 63849026L,
    'encrypt_type': 1,
    'reserved2': 1,
    'spcoding': 16,
    'splvalue': 0,
    'stored_len': 42496L,
    'stored_md5': 'a763a97070c8aedaaebd522f4a5d83af',
    'target': 'm1200',
    'target_name': 'electronic speed control 0',
    'version': '01.11.0000'}
WM610_v01.11.01.50.bin: Module index 13
{   'decrypted_len': 42496L,
    'decrypted_md5': '108b07f5fa7d52a9781a905de97b7897',
    'dt_offs': 63891522L,
    'encrypt_type': 1,
    'reserved2': 1,
    'spcoding': 16,
    'splvalue': 0,
    'stored_len': 42496L,
    'stored_md5': 'a763a97070c8aedaaebd522f4a5d83af',
    'target': 'm1201',
    'target_name': 'electronic speed control 1',
    'version': '01.11.0000'}
WM610_v01.11.01.50.bin: Module index 14
{   'decrypted_len': 42496L,
    'decrypted_md5': '108b07f5fa7d52a9781a905de97b7897',
    'dt_offs': 63934018L,
    'encrypt_type': 1,
    'reserved2': 1,
    'spcoding': 16,
    'splvalue': 0,
    'stored_len': 42496L,
    'stored_md5': 'a763a97070c8aedaaebd522f4a5d83af',
    'target': 'm1202',
    'target_name': 'electronic speed control 2',
    'version': '01.11.0000'}
WM610_v01.11.01.50.bin: Module index 15
{   'decrypted_len': 42496L,
    'decrypted_md5': '108b07f5fa7d52a9781a905de97b7897',
    'dt_offs': 63976514L,
    'encrypt_type': 1,
    'reserved2': 1,
    'spcoding': 16,
    'splvalue': 0,
    'stored_len': 42496L,
    'stored_md5': 'a763a97070c8aedaaebd522f4a5d83af',
    'target': 'm1203',
    'target_name': 'electronic speed control 3',
    'version': '01.11.0000'}
WM610_v01.11.01.50.bin: Module index 16
{   'decrypted_len': 79676L,
    'decrypted_md5': '8d9550c03b799ec3692173e200851287',
    'dt_offs': 64019010L,
    'encrypt_type': 0,
    'reserved2': 1,
    'spcoding': 0,
    'splvalue': 0,
    'stored_len': 79676L,
    'stored_md5': '8d9550c03b799ec3692173e200851287',
    'target': 'm1700',
    'target_name': "visual positioning module 'camera'",
    'version': '01.01.0008'}
WM610_v01.11.01.50.bin: Module index 17
{   'decrypted_len': 26516L,
    'decrypted_md5': 'b8387b166b9805d60c30d1c79d228294',
    'dt_offs': 64098686L,
    'encrypt_type': 0,
    'reserved2': 1,
    'spcoding': 0,
    'splvalue': 0,
    'stored_len': 26516L,
    'stored_md5': 'b8387b166b9805d60c30d1c79d228294',
    'target': 'm1701',
    'target_name': "visual positioning module 'sonar'",
    'version': '02.00.0262'}
WM610_v01.11.01.50.bin: Headers checksum 8E48 matches.
WM610_v01.11.01.50.bin: Extracting module index 0, 62009668 bytes
WM610_v01.11.01.50.bin: Module index 0 stored checksum e1c16545022bef29c6ab012067403172
WM610_v01.11.01.50.bin: Extracting module index 1, 420048 bytes
WM610_v01.11.01.50.bin: Module index 1 stored checksum 1cdc519e82be535e144cdad3d94e4d0c
WM610_v01.11.01.50.bin: Extracting module index 2, 34916 bytes
WM610_v01.11.01.50.bin: Module index 2 stored checksum d85da1e3804548f16e2b22e9b04a0d8c
WM610_v01.11.01.50.bin: Extracting module index 3, 42496 bytes
Error: IV must be 16 bytes long
`

**Comment by mefistotelis** [comment]
Note that there is a hash-bang line at the beginning of each script, stating it expects Python 3. All scripts should work fine on Python 3.7+.

Also, look at:
https://github.com/o-gs/dji-firmware-tools/issues/101
https://github.com/o-gs/dji-firmware-tools/issues/90
