### ISSUE TITLE
No connection to Mavic Pro 2 Gimbal

### ISSUE THREAD

**Issue by DerKlotz74** [o-gs/dji-firmware-tools#187]
Hi, i have problems to run " py comm_og_service_tool.py com6 WM240 GimbalCalib JointCoarse". I receive the following error message: 
"Traceback (most recent call last):
 File "comm_og_service_tool.py", line 35 , in  <module> 
 import serial
ModuleNotFoundError: No module named ´serial´
Somebody an idea.

**Comment by mefistotelis** [comment]
Try reading the error message. Google it if you must.

**Comment by mc197910** [comment]
hi need help

**Comment by DerKlotz74** [comment]
> 
> 
> Hi, i have problems to run " py comm_og_service_tool.py com6 WM240 GimbalCalib JointCoarse". I receive the following error message:
> "Traceback (most recent call last):
> File "comm_og_service_tool.py", line 35 , in
> import serial
> ModuleNotFoundError: No module named ´serial´
> Somebody an idea.

I sold the camera... Thanks
