### ISSUE TITLE
Phantom 4 séries calibraçao motor yaw 

### ISSUE THREAD

**Issue by tecdrone** [o-gs/dji-firmware-tools#197]
Olá amigos quem já conseguiu encontra a solução de calibração para os gimbal Phantom 4

**Comment by mefistotelis** [comment]
Duplicate of #99 
Write in English!

**Comment by tecdrone** [comment]
Hello friends who already found the calibration solution for the Phantom 4 gimbal

**Comment by rameez1998** [comment]
not found yet :(

**Comment by jefsilv** [comment]
Hoo my god , I need this cod ...much much

**Comment by jefsilv** [comment]
For the Mavic mini gimbal too, will the mavic code be right?

**Comment by robisonb** [comment]
Olá amigo vcs já tem o programa para calibrar o gimbal do phantom 4 séries ???
