### ISSUE TITLE
Phantom 4 series gimbal calibration after changing the esc board and yaw engine

### ISSUE THREAD

**Issue by tecdrone** [o-gs/dji-firmware-tools#198]
hello everyone I would like to know.  how to extract by rx tx using TTL to can do Phantom 4 gimbal calibration

**Comment by rsrmdp** [comment]
https://github.com/o-gs/dji-firmware-tools

**Comment by mefistotelis** [comment]
https://github.com/o-gs/dji-firmware-tools/issues/99
