### ISSUE TITLE
P3P "visible" wifi ? 

### ISSUE THREAD

**Issue by KennethMcNutt** [o-gs/dji-firmware-tools#21]
I am simply  looking for a way to get into the Wifi parameters.. To increase the output level of the P3P...
I have Used the ftp method on the P3S.. To set it... But there is no method of doing this to the P3P.. It maybe just my ignorance that is stopping me?? I have found all of this info.. But I don't see a way into the settings like in the "MagicPower" Mod for the P3S... I also found in the links below.. A reference to enabling the "wifi" it is from the 1.8.8 bin file.. But I have seen it found in the P3S controller .config.. By Enabling the P3P to have a "Visible" Wifi that you can connect to.. Does two things..
First it is a way into the system.. (ftp) 
and also away for it to be "repeated" like I have done with my P3S .. (with any "wireless extender") http://forum.dji.com/thread-58369-1-1.html <this is what was found in the P3S config
[Powermagiclog.txt](https://github.com/mefistotelis/phantom-firmware-tools/files/788619/Powermagiclog.txt) <this is a update log from MagicPower..
[P3Ppasswords.txt](https://github.com/mefistotelis/phantom-firmware-tools/files/788628/P3Ppasswords.txt) This is all the system passwords I could come up with..
[1.8.8hexbindump.txt](https://github.com/mefistotelis/phantom-firmware-tools/files/788636/1.8.8hexbindump.txt)< this is what I found in the 1.8.8 bin with a Hex editor.. 

So Again is there anyone that can Understand all this? Is there a way to mod a bin file to turn on the "WiFi"??

**Comment by mefistotelis** [comment]
What gave you an idea that there is a wi-fi chip somewhere in P3P?
On which board have you seen it?

P3P/P3A is completely different hardware than P3S/P3-4k. There is no point in comparing these.

**Comment by KennethMcNutt** [comment]
Only because I was using a Hex editor.. And found this in 1.8.8 pro firmware?? That is why I thought it was possible ... I have not looked at the board for a chip... I just saw no reason for the Info to be in PRO firmware? Right?
https://github.com/mefistotelis/phantom-firmware-tools/files/788636/1.8.8hexbindump.txt
That is from the 1.8.8 bin file..

**Comment by KennethMcNutt** [comment]
Do you have a reason .. that explains why Pro firmware has that in it's bin? I don't see any reason the P3S and the P3P would share programing??

**Comment by mefistotelis** [comment]
Have you ever looked at "firmware" of your PC? I mean, the operating system you're using. It has tons of drivers inside; do you have hardware to use all of them?

If you still want to dig deeper, start by checking which firmware module has the wifi config.

**Comment by KennethMcNutt** [comment]
Yes that is understandable.. But PC'S are not hardware specific.. Like the p3... Assuming that.. It seems that that code it found is truly useless? There is no Plug and play LOL

**Comment by mefistotelis** [comment]
Again:
If you still want to dig deeper, start by checking which firmware module has the wifi mention.

Otherwise we're doing a theoretical discussion.

**Comment by KennethMcNutt** [comment]
I am truly ignorant.. I will have to learn much!! I will start with that... :) Thank you Sir!!!

**Comment by KennethMcNutt** [comment]
Can you point me ?? I would look in the modules... But have not a clue how to start.. I would like to be involed with this (backward engineering...) But I have much to learn.. Please forgive me.. Linux , coding, programing are not my forte...I understand the theory, But I have no practical use experience :( this is also what I found in the 1.8.8 bin..
# Atheros..if [ -e /sys/module/ar6000 ]; then...return 0..fi...# Broadcom..if [ -e /sys/module/dhd ]; then...return 0..fi...return 1.}..hostapd_conf().{..if [ "${usecache}" != "" ] && [ -e /tmp/hostapd.conf ]; then...cat /tmp/hostapd.conf..else...#generate hostapd.conf...echo "interface=wlan0" > /tmp/hostapd.conf...echo "ctrl_interface=/var/run/hostapd" >> /tmp/hostapd.conf...echo "beacon_int=100" >> /tmp/hostapd.conf...echo "dtim_period=1" >> /tmp/hostapd.conf...echo "preamble=0" >> /tmp/hostapd.conf...#WPS support...echo "wps_state=2" >> /tmp/hostapd.conf...echo "eap_server=1" >> /tmp/hostapd.conf....#AP_SSID...AP_SSID=`echo "${conf}" | grep AP_SSID | cut -c 9-`...echo "AP_SSID=${AP_SSID}"...echo "ssid=${AP_SSID}" >> /tmp/hostapd.conf....#AP_MAXSTA...AP_MAXSTA=`echo "${conf}" | grep AP_MAXSTA | cut -c 11-`...echo "max_num_sta=${AP_MAXSTA}" >> /tmp/hostapd.conf....#AP_CHANNEL...AP_CHANNEL=`echo "${conf}" | grep AP_CHANNEL | cut -c 12-`...if [ ${AP_CHANNEL} -lt 0 ]; then....reset_conf....return 1...fi....# TODO: For 5G?!...if [ ! -e /sys/module/ar6000 ] && [ $AP_CHANNEL -eq 0 ]; then....#choose 1~10 for HT40....#RAND_CHANNEL=`echo $(( $RANDOM % 10 +1 ))`....RAND_CHANNEL=`echo $(( ($RANDOM % 3) * 5 + 1 ))`....echo "channel=${RAND_CHANNEL}" >> /tmp/hostapd.conf...fi...if [ $AP_CHANNEL -ne 0 ]; then....echo "channel=${AP_CHANNEL}" >> /tmp/hostapd.conf...else....AP_CHANNEL=${RAND_CHANNEL}....echo "AP_CHANNEL (randomly)=${AP_CHANNEL}"...fi....#WEP, WPA, No Security...AP_PUBLIC=`echo "${conf}" | grep AP_PUBLIC | cut -c 11- | tr '[:lower:]' '[:upper:]'`...echo "AP_PUBLIC=${AP_PUBLIC}"...if [ "${AP_PUBLIC}" != "YES" ]; then....#WPA....echo "wpa=2" >> /tmp/hostapd.conf....echo "wpa_pairwise=CCMP" >> /tmp/hostapd.conf....AP_PASSWD=`echo "${conf}" | grep AP_PASSWD | cut -c 11-`....echo "wpa_passphrase=${AP_PASSWD}" >> /tmp/hostapd.conf....echo "wpa_key_mgmt=WPA-PSK" >> /tmp/hostapd.conf...fi....# Check nl80211...chk_nl80211...rval=$?...if [ ${rval} -eq 1 ]; then....echo "driver=nl80211" >> /tmp/hostapd.conf....if [ ${AP_CHANNEL} -gt 14 ]; then.....echo "hw_mode=a" >> /tmp/hostapd.conf....else.....echo "hw_mode=g" >> /tmp/hostapd.conf....fi....echo "ieee80211n=1" >> /tmp/hostapd.conf....if [ ! -e /sys/module/bcmdhd ]; then.....# TODO: Support HT40 for 5G.....if [ ${AP_CHANNEL} -lt 6 ]; then......# HT40+ for 1-7 (1-9 in Europe/Japan)......echo "ht_capab=[SHORT-GI-20][SHORT-GI-40][HT40+]" >> /tmp/hostapd.conf.....else......# HT40- for 5-13......echo "ht_capab=[SHORT-GI-20][SHORT-GI-40][HT40-]" >> /tmp/hostapd.conf.....fi....fi....#echo "wme_enabled=1" >> /tmp/hostapd.conf....#echo "wpa_group_rekey=86400" >> /tmp/hostapd.conf...fi..fi.}..wpa_supplicant_conf().{..if [ -e /sys/module/ar6000 ]; then...driver=wext..else...driver=nl80211..fi...if [ "${usecache}" != "" ] && [ -e /tmp/wpa_supplicant.ap.conf ]; then...cat /tmp/wpa_supplicant.ap.conf..else...#generate /tmp/wpa_supplicant.ap.conf...echo "ctrl_interface=/var/run/wpa_supplicant" > /tmp/wpa_supplicant.ap.conf...echo "ap_scan=2" >> /tmp/wpa_supplicant.ap.conf....#AP_MAXSTA...AP_MAXSTA=`echo "${conf}" | grep AP_MAXSTA | cut -c 11-`...echo "max_num_sta=${AP_MAXSTA}" >> /tmp/wpa_supplicant.ap.conf....echo "network={" >> /tmp/wpa_supplicant.ap.conf...#AP_SSID...AP_SSID=`echo "${conf}" | grep AP_SSID | cut -c 9-`...echo "AP_SSID=${AP_SSID}"...echo "ssid=\"${AP_SSID}\"" >> /tmp/wpa_supplicant.ap.conf....#AP_CHANNEL...AP_CHANNEL=`echo "${conf}" | grep AP_CHANNEL | cut -c 12-`...echo "AP_CHANNEL=${AP_CHANNEL}"...if [ ${AP_CHANNEL} -lt 0 ]; then....reset_conf....return 1...fi....# TODO: for 5G...if [ $AP_CHANNEL -eq 0 ]; then....#choose 1~10 for HT40....#AP_CHANNEL=`echo $(( $RANDOM % 11 +1 ))`....AP_CHANNEL=`echo $(( ($RANDO1...èžmxæ.......0.......g...... ................M % 3) * 5 + 1 ))`...fi....# cf. http://en.wikipedia.org/wiki/List_of_WLAN_channels...if [ $AP_CHANNEL -lt 14 ]; then....# 2.4G: 2412 + (ch-1) * 5....echo "frequency=$((2412 + ($AP_CHANNEL - 1) * 5))" >> /tmp/wpa_supplicant.ap.conf...else....# 5G: 5000 + ch * 5....echo "frequency=$((5000 + $AP_CHANNEL * 5))" >> /tmp/wpa_supplicant.ap.conf...fi....#WEP, WPA, No Security...AP_PUBLIC=`echo "${conf}" | grep AP_PUBLIC | cut -c 11- | tr '[:lower:]' '[:upper:]'`...if [ "${AP_PUBLIC}" != "YES" ]; then....# proto defaults to: WPA RSN....echo "proto=WPA2" >> /tmp/wpa_supplicant.ap.conf....echo "pairwise=CCMP" >> /tmp/wpa_supplicant.ap.conf....echo "group=CCMP" >> /tmp/wpa_supplicant.ap.conf....AP_PASSWD=`echo "${conf}" | grep AP_PASSWD | cut -c 11-`....echo "psk=\"${AP_PASSWD}\"" >> /tmp/wpa_supplicant.ap.conf....echo "key_mgmt=WPA-PSK" >> /tmp/wpa_supplicant.ap.conf...else....echo "key_mgmt=NONE" >> /tmp/wpa_supplicant.ap.conf...fi...echo "mode=2" >> /tmp/wpa_supplicant.ap.conf...echo "}" >> /tmp/wpa_supplicant.ap.conf...if [ -e /sys/module/bcmdhd ]; then....echo "p2p_disabled=1" >> /tmp/wpa_supplicant.ap.conf...fi..fi.}..bcm_ap_start().{..#AP_SSID..AP_SSID=`echo "${conf}" | grep AP_SSID | cut -c 9-`..echo "AP_SSID=${AP_SSID}"...#AP_MAXSTA..AP_MAXSTA=`echo "${conf}" | grep AP_MAXSTA | cut -c 11-`..echo "AP_MAXSTA=${AP_MAXSTA}"...#AP_CHANNEL..AP_CHANNEL=`echo "${conf}" | grep AP_CHANNEL | cut -c 12-`..echo "AP_CHANNEL=${AP_CHANNEL}"..if [ ${AP_CHANNEL} -lt 0 ]; then...reset_conf...return 1..fi..if [ $AP_CHANNEL -eq 0 ]; then...#choose 1~10 for HT40...#AP_CHANNEL=`echo $(( $RANDOM % 11 +1 ))`...AP_CHANNEL=`echo $(( ($RANDOM % 3) * 5 + 1 ))`...echo "Random AP_CHANNEL=${AP_CHANNEL}"..fi...ifconfig wlan0 down..wl down..wl ap 0..wl ap 1..wl ssid "$AP_SSID"..#wl bssmax $AP_MAXSTA..wl channel $AP_CHANNEL...#WEP, WPA, No Security..AP_PUBLIC=`echo "${conf}" | grep AP_PUBLIC | cut -c 11- | tr '[:lower:]' '[:upper:]'`..echo "AP_PUBLIC=${AP_PUBLIC}"...# auth: set/get 802.11 authentication. 0 = OpenSystem, 1 = SharedKey, 2 = Open/Shared...# wpa_auth..#.Bitvector of WPA authorization modes:..#.1    WPA-NONE..#.2    WPA-802.1X/WPA-Professional..#.4    WPA-PSK/WPA-Personal..#.64   WPA2-802.1X/WPA2-Professional..#.128  WPA2-PSK/WPA2-Personal..#.0    disable WPA..if [ "${AP_PUBLIC}" != "YES" ]; then...wl wpa_auth 128....# wsec  wireless security bit vector...#.1 - WEP enabled...#.2 - TKIP enabled...#.4 - AES enabled...#.8 - WSEC in software...#.0x80 - FIPS enabled...#.0x100 - WAPI enabled...wl wsec 4....AP_PASSWD=`echo "${conf}" | grep AP_PASSWD | cut -c 11-`...echo "AP_PASSWD=${AP_PASSWD}"...wl set_pmk "$AP_PASSWD"..else...wl auth 0...wl wpa_auth 0...wl wsec 0..fi...wl mpc 0..wl frameburst 1..wl up..ifconfig wlan0 up...return 0.}..apply_ap_conf().{..#LOCAL_IP..LOCAL_IP=`echo "${conf}" | grep LOCAL_IP | cut -c 10-`..killall udhcpc..ifconfig wlan0 $LOCAL_IP..if [ $? -ne 0 ]; then...reset_conf...return 1..fi..route add default gw $LOCAL_IP...#LOCAL_NETMASK..LOCAL_NETMASK=`echo "${conf}" | grep LOCAL_NETMASK | cut -c 15-`..ifconfig wlan0 netmask $LOCAL_NETMASK..if [ $? -ne 0 ]; then...reset_conf...return 1..fi...#DHCP_IP_START DHCP_IP_END..DHCP_IP_START=`echo "${conf}" | grep DHCP_IP_START | cut -c 15-`..DHCP_IP_END=`echo "${conf}" | grep DHCP_IP_END | cut -c 13-`..dnsmasq --nodns -5 -K -R -n --dhcp-range=$DHCP_IP_START,$DHCP_IP_END,infinite..if [ $? -ne 0 ]; then...reset_conf...return 1..fi...if [ -e /sys/module/dhd ]; then...# Broadcom bcm43362, etc....bcm_ap_start...rval=$?..else...which hostapd...if [ $? -ne 0 ] || [ -e /sys/module/ath6kl_sdio ]; then....wpa_supplicant_conf....rval=$?....if [ ${rval} -ne 0 ]; then.....reset_conf.....return 1....fi....wpa_supplicant -D${driver} -iwlan0 -c/tmp/wpa_supplicant.ap.conf -B....rval=$?...else....hostapd_conf....rval=$?....if [ ${rval} -ne 0 ]; then.....reset_conf.....return 1....fi....hostapd -B /tmp/hostapd.conf....rval=$?...fi..fi...if [ ${rval} -ne 0 ]; then...reset_conf...return 1..fi..if [ -e /sys/module/ar6000 ] && [ $AP_CHANNEL -eq 0 ]; then...#ACS (Automatic Channel Selection) between 1, 6, 11...i1...« Léç.......ì.......g...... ........¼.......wconfig wlan0 channel 0...iwconfig wlan0 commit..fi...#send wifi status update message (Wifi On, AP mode, need to do wifi_postproc)..#SendToItron 0xf403002c 2 1..boot_done 1 2 1...return 0.}..#Load the parameter settings.if [ "${conf}" == "" ]; then..conf=`cat /pref/wifi.conf | grep -Ev "^#"`.fi.apply_ap_conf.rval=$?.echo -e "rval=${rval}\n".if [ ${rval} -ne 0 ]; then..killall -9 hostapd wpa_supplicant dnsmasq 2>/dev/null..apply_ap_conf.fi.ÿÿÿÿ1...x´Y.è....... .......g...............ä.......¼!......s×€V....vÞ.V....Î.öS............................í.......................................................1...Yõ†Žé.......D.......T...%W/D........g...............ap_start.sh.ÿÿÿÿ1....ÿ..ë.......Ç.......h...... ........—.......#!/bin/sh..if [ "$1" = "host" ]; then.    echo host > /proc/ambarella/uport.elif [ "$1" = "device" ]; then.    echo device > /proc/ambarella/uport.fi..ÿ1...¹®ë!ì....... .......h...............ê.......—.......s×€V....IØ€V....IØ€V............................í.......................................................1...&Ð).í.......A.......T...M.—B........h...............usbsw.sh.ÿÿÿÿÿÿÿ1...`2..ï.......w.......i...... ........G.......#!/bin/sh..TXPKT=0.TXPKTPRE=0.TXBYTE=0.TXBYTEPRE=0.RXFRM=0.RXFRMPRE=0..printf "RxFr TxPkt TxByte\n".printf "0000 00000 00000000".TXPKTPRE=`ifconfig usb0 | sed -n '5p' | awk '{print $2}' | awk -F : '{print $2}'`.TXBYTEPRE=`ifconfig usb0 | sed -n '7p' | awk -F : '{print $3}' | awk '{print $1}'`.RXFRMPRE=`cat /proc/dji/trans/stat | sed -n '9p' | awk '{print $4}'`.while true.do.    TXPKT=`ifconfig usb0 | sed -n '5p' | awk '{print $2}' | awk -F : '{print $2}'`.    TXBYTE=`ifconfig usb0 | sed -n '7p' | awk -F : '{print $3}' | awk '{print $1}'`.    RXFRM=`cat /proc/dji/trans/stat | sed -n '9p' | awk '{print $4}'`.    printf "\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b".    printf "%4u %5u %8u" $((RXFRM - RXFRMPRE)) $((TXPKT - TXPKTPRE)) $((TXBYTE - TXBYTEPRE)).    TXPKTPRE=$TXPKT.    TXBYTEPRE=$TXBYTE.    RXFRMPRE=$RXFRM.    sleep 1.done..ÿ1...¨Mvpð....... .......i...............î.......G.......s×€V....âá.V....âá.V............................í.......................................................1...fò..ñ.......@.......T....µŸR........i...............test.sh.1...o¤.Ìó...............j...... ........æ.......#!/bin/sh.cd /.#echo -e "\nPress CTRL+C now if you want to skip hibernation".#sleep 1..#sync.#echo 3 > /proc/sys/vm/drop_caches..#echo disk > /sys/power/state..echo -e "\nskip hibernation"... /usr/local/share/script/sync_rtc.sh...ÿÿ1....‚–.ô....... .......j...............ò.......æ.......s×€V....IØ€V....IØ€V............................í.......................................................1...J.âÓõ.......G.......T...acjR........j...............ambernation.sh.ÿ1...§MMu÷.......”.......k...... ........d.......#!/bin/sh.echo "$0 $@".HCI_DRIVER=`cat /pref/bt.conf | grep -Ev "^#" | grep HCI_DRIVER | cut -c 12-`.if [ "${HCI_DRIVER}" == "ath3k" ]; then..if [ $1 -ge 15 ]; then...echo hcitool cmd 0x3f 0x13 0x04 0x0 0x0 0x0 0x4 0x0 0x0 0x0...hcitool cmd 0x3f 0x13 0x04 0x0 0x0 0x0 0x4 0x0 0x0 0x0..elif [ $1 -ge 12 ]; then...echo hcitool cmd 0x3f 0x13 0x04 0x0 0x0 0x0 0x3 0x0 0x0 0x0...hcitool cmd 0x3f 0x13 0x04 0x0 0x0 0x0 0x3 0x0 0x0 0x0..elif [ $1 -ge 8 ]; then...echo hcitool cmd 0x3f 0x13 0x04 0x0 0x0 0x0 0x2 0x0 0x0 0x0...hcitool cmd 0x3f 0x13 0x04 0x0 0x0 0x0 0x2 0x0 0x0 0x0..elif [ $1 -ge 4 ]; then...echo hcitool cmd 0x3f 0x13 0x04 0x0 0x0 0x0 0x1 0x0 0x0 0x0...hcitool cmd 0x3f 0x13 0x04 0x0 0x0 0x0 0x1 0x0 0x0 0x0..elif [ $1 -ge 0 ]; then...echo hcitool cmd 0x3f 0x13 0x04 0x0 0x0 0x0 0x0 0x0 0x0 0x0...hcitool cmd 0x3f 0x13 0x04 0x0 0x0 0x0 0x0 0x0 0x0 0x0..fi.fi.ÿÿÿÿ1...Ñ.lÜø....... .......k...............ö.......d.......s×€V....vÞ.V....Î.öS............................í.......................................................1...P'Ì¸ù.......J.......T...RàLI........k...............bt_speakergain.sh.ÿÿÿÿÿÿ1...ó[‘eû...............l...... ........ç.......#!/bin/sh..if [ $# -ne 2 ]; then..echo "usage: $0 93 0"..exit 0.fi..proc_gpio().{..echo "t gpio ${1} sw out${2}"...gpiohex=`printf %02x ${1}`...# "C"onfig gpio sw output (0x1)..echo -en 'c\x'"${gpiohex}"'\x01' > /proc/ambarella/gpio...if [ "${2}" == "0" ]; then...# "W"rite output 1(0x0)...echo -en 'w\x'"${gpiohex}"'\x00' > /proc/ambarella/gpio..fi...if [ "${2}" == "1" ]; then...# "W"rite output 1(0x1)...echo -en 'w\x'"${gpiohex}"'\x01' > /proc/ambarella/gpio..fi.}..sys_gpio().{..echo "t gpio ${1} sw out${2}"...if [ ! -e /sys/class/gpio/gpio${1} ]; then...cd /sys/class/gpio/...echo ${1} > export...cd gpio${1}/...echo out > direction..fi...if [ -e /sys/class/gpio/gpio${1} ]; then...cd /sys/class/gpio/gpio${1}/...if [ "${2}" == "0" ]; then....echo 0 > value...elif [ "${2}" == "1" ]; then....echo 1 > value...fi..fi.}..if [ -e /proc/ambarella/gpio ]; then..proc_gpio ${1} ${2}.elif [ -e /sys/class/gpio ]; then..sys_gpio ${1} ${2}.else..echo "/proc/ambarella/gpio does not exist"..exit 0.fi..ÿ1...ïf..ü....... .......l...............ú.......ç.......s×€V....vÞ.V....Î.öS............................í.......................................................1...§.ï+ý.......B.......T...rŸ0X........l...............t_gpio.sh.ÿÿÿÿÿÿ1...«xxîÿ.......'.......m...... ........÷.......##### Wifi configuration file ##########################################.## Empty lines and lines starting with # are ignored.# ap: SoftAP mode.# sta: Station mode.# p2p: Enable Wifi Direct Support for peer-to-peer connectibity.WIFI_MODE=ap.# GPIO pin to enable or disable WiFi.#WIFI_EN_GPIO=95..##### STA mode configuration ##########################################.# SSID.ESSID=amba_boss.# Passphrase. Leave empty at no security mode; please edit wpa_supplicant.conf when your AP cannot be detected.PASSWORD=1234567890.# Device Name for AMBA Discovery Protocol (optional).STA_DEVICE_NAME=amba-1.# Do not detect SSID setting changes, use previous scanned results.STA_SKIP_SCAN=yes..##### Wifi Direct configuration ##########################################.# Find devices with correct name prefix and automatically connect at startup.P2P_AUTO_CONNECT=no.# Auto-connect with devices if the name prefix matches.P2P_CONNECT_PREFIX=amba.## Do not enable this optional field unless you are certain.# please provide a unique name amoung multiple devices to prevent confusion.#P2P_DEVICE_NAME=amba-1.## Do not enable this optional field unless you are certain.# Set the default P2P GO Intent.#P2P_GO_INTENT=0.## Do not enable this optional field unless you are certain.# Specify P2P operating channel.#P2P_OPER_CHANNEL=1.## Do not enable this optional field unless you are certain.# Default mode for HT40 enable when operating as GO.#P2P_GO_HT40=0..##### SoftAP configuration ##########################################.# SSID (1 ~ 32 characters).AP_SSID=amba_boss.# IP address.LOCAL_IP=192.168.42.1.# IP subnet mask.LOCAL_NETMASK=255.255.255.0.# IP pool starting address of DHCP server.DHCP_IP_START=192.168.42.2.# IP pool end address of DHCP server.DHCP_IP_END=192.168.42.6.# Wifi channel number, set 0 to use Auto Channel Selection.AP_CHANNEL=0.# Maximum number of stations allowed in station table.AP_MAXSTA=5.# If you say yes here, all WPA/WEP settings will be ignored.AP_PUBLIC=no.# WPA Passphrase (8 ~ 63 characters).AP_PASSWD=1234567890.ÿ1...¬³eS........ .......m...............þ.......÷.......s×€V....vÞ.V....Î.öS............................í.......................................................1...µ;5Y........B.......T...ÑX±S........m...............wifi.conf.ÿÿÿÿÿÿ1...þ. .........ð.......n...... ........À.......WIFI_MODE=ap.AP_SSID=amba_boss.LOCAL_IP=192.168.42.1.LOCAL_NETMASK=255.255.255.0.DHCP_IP_START=192.168.42.2.DHCP_IP_END=192.168.42.6.AP_CHANNEL=8.AP_MAXSTA=5.AP_PUBLIC=no.AP_PASSWD=1234567890.1...qÙú?........ .......n.......................À.......s×€V....vÞ.V....Î.öS............................í.......................................................1...Þ.Ù.........E.......T...zÙïU........n...............wifi.ap.conf.ÿÿÿ1...+.¿ž................o...... ........_.......#!/bin/sh.#This script is used to mount/umount sd card in ambafs..#$1: mount or umount.#$2: target directory.#$3: source device.#$4: file system type..if [ "$1" = "mount" ]; then..STR=$3" on "$2" type "$4..RET=`mount | grep "$STR"`..if [ -z "$RET" ]; then...echo $STR...RET=`mount -t $4 $3 $2`..fi.fi..if [ "$1" = "umount" ]; then..RET=`umount $2`.fi.ÿ1...Ã1,Ý........ .......o......................._.......s×€V.....à.V.....à.V............................í.......................................................1...¶ø«Ú........E.......T....kÂ_........o...............sd_script.sh.ÿÿÿ1...ŒöM\........·.......p...... ........‡.......##### this config file will only be used when your AP cannot be detected.## WPA2-PSK-CCMP        (11n requirement).#ctrl_interface=/var/run/wpa_supplicant.#network={.#ssid="Amba_AP".#key_mgmt=WPA-PSK.#proto=WPA2.#pairwise=CCMP.#psk="PWFORAMBA".#}..## WPA-PSK-TKIP.#ctrl_interface=/var/run/wpa_supplicant.#network={.#ssid="Amba_AP".#key_mgmt=WPA-PSK.#proto=WPA.#pairwise=TKIP.#psk="PWFORAMBA".#}..## WEP.#ctrl_interface=/var/run/wpa_supplicant.#network={.#ssid="Amba_AP".#key_mgmt=NONE.#wep_key0="72a4b4b91b".#wep_key1=0102030405.#wep_tx_keyidx=0.#}..## no security.ctrl_interface=/var/run/wpa_supplicant.network={.ssid="amba_boss".key_mgmt=NONE.}.ÿ1...^\û„........ .......p.......................‡.......s×€V....vÞ.V....Î.öS............................¤.......................................................1...º·©4........L.......T...ªë¦T........p...............wpa_supplicant.conf.ÿÿÿÿ1...rXm‡........S.......q...... ........#.......#!/bin/sh..wait_wlan0().{..n=0..ifconfig wlan0..waitagain=$?..while [ $n -ne 6 ] && [ $waitagain -ne 0 ]; do...n=$(($n + 1))...echo $n...sleep 1...ifconfig wlan0...waitagain=$?..done.}..killall hostapd dnsmasq udhcpc wpa_supplicant wpa_cli wpa_event.sh 2> /dev/null.killall hostapd dnsmasq udhcpc wpa_supplicant wpa_cli wpa_event.sh 2> /dev/null..if [ ! -e /tmp/wifi.loaded ]; then../usr/local/share/script/load.sh sta..wait_wlan0.fi..if [ -e /sys/module/ar6000 ]; then..driver=wext.else..driver=nl80211.fi..if [ "${1}" == "" ]; then..echo "specify SSID to connect, for example ${0} amba_boss"..exit 0.fi..cp /usr/local/share/script/wpa_supplicant.conf /tmp/.sed -i 's|amba_boss|'${1}'|g' /tmp/wpa_supplicant.conf.wpa_supplicant -D${driver} -iwlan0 -c/tmp/wpa_supplicant.conf -B.udhcpc -i wlan0 -A 1 -b.ÿÿÿÿÿ1...ýP$;........ .......q.......................#.......s×€V....vÞ.V....Î.öS............................í.......................................................1...’òµà........?.......T...IÕXV........q...............sta.sh.ÿ1...¯o¤Í........“.......r...... ........c.......#!/bin/sh..KVER=3.8.0..if [ ! -e /tmp/wifi.preloaded ]; then../usr/local/share/script/preload.sh.fi.rm /tmp/wifi.preloaded..mac=`cat /tmp/wifi0_mac`.if [ "${mac}" != "00:00:00:00:00:00" ] &&  [ "${mac}" != "" ]; then..echo "mac: ${mac}, but no use"..fi..#insmod /lib/modules/${KVER}/updates/drivers/net/wireless/realtek/8192eu.ko..touch /tmp/wifi.loaded..ÿÿÿÿÿ1...º7í«........ .......r.......................c.......s×€V....IØ€V....IØ€V............................é.......................................................1...lwÝ–........@.......T...·õ®J........r...............load.sh.1...y.Àú................s...... ........Ò.......#!/bin/sh.sysl=`ps | grep syslogd | grep -v grep`.LOGGER ().{..if [ "${sysl}" == "" ]; then...echo "$@"..else...logger "$@"..fi.}..sleep 0.5.LOGGER "$@"..HCI_LE_Set_Advertising_Parameters ().{..LE_Controller_Commands_OGF=0x08..HCI_LE_Set_Advertising_Parameters_OCF=0x0006..#500 ms..Advertising_Interval_Min="20 03"..#4 sec..Ad

**Comment by mefistotelis** [comment]
What you have here looks like a part of Linux partition from the Ambarella module. You should have written that.

Unless you haven't really extracted separate modules, in which case you should get the tools which are being developed in this GIT repository, and learn how to use them from README.

If you want to extract strings from a firmware, it is best to use "strings" command from binutils package.

**Comment by mefistotelis** [comment]
One more thing - note that modifying the firmware without extracting modules will not work anyway, because the firmware contains checksums. Modify without extraction -> checksum becomes invalid.
