### ISSUE TITLE
Phantom 3 boards photos request

### ISSUE THREAD

**Issue by mefistotelis** [o-gs/dji-firmware-tools#22]
It would help in hacking if we had sharp pictures of all the boards making up Phantom 3 Pro/Adv (both Aircraft and RC).

@notsolowki already prepared photos of camera top board - these are not perfect, but did helped me a lot:
https://github.com/mefistotelis/phantom-firmware-tools/issues/5#issuecomment-270053099

The photos should be in good enough quality so that the markings on chips are readable; if they're not - it is best to follow whole board photo by a close-up on parts of the board, and find an angle at which the markings are well visible.

We need photos of both sides of each board.

Photos of the main controller board are easy to find in google; but I wasn't able to find good photos of the RC internals.

**Comment by MrBurnsAT** [comment]
Ill open my GL300B and make Photos the next Days!

**Comment by neven385** [comment]
Count me in for GL300C. I'll take some pics today.

**Comment by MrBurnsAT** [comment]
http://www.phantompilots.com/attachments/dsc03660_cr-jpg.28141/

This should be back side if 300B

**Comment by neven385** [comment]
![sam_1408](https://cloud.githubusercontent.com/assets/25346476/23363792/ac2e4558-fcfc-11e6-9be1-93e1cbee13e8.JPG)

**Comment by notsolowki** [comment]
Heres a couple of pics of the rc board. Therly are not the best i took then long ago.
![20170207_100954](https://cloud.githubusercontent.com/assets/24588286/23367249/2f1c8f48-fccf-11e6-80bc-63629bef514c.jpg)
![20170207_101002](https://cloud.githubusercontent.com/assets/24588286/23367280/51ed4256-fccf-11e6-8fd8-2c28ab32d4dc.jpg)

**Comment by mefistotelis** [comment]
I found this about GL300C:
http://www.sb-dji.com/?p=12751

But I don't think GL300A uses the same components. For example the ARM firmware which I worked on has striking resemblance to LPC17xx series, and there are major differences between it and the LPC1549 used in GL300C.

Anyone can share pictures of chips from A or B?

**Comment by mefistotelis** [comment]
I've checked mine, but the USB board only:

![gl300a_usb_front_dsc_7458-net](https://cloud.githubusercontent.com/assets/11463396/23543886/a5cc2e14-fff4-11e6-9ebc-7aca22f6f2f9.jpg)
![gl300a_usb_front_dsc_7461-net](https://cloud.githubusercontent.com/assets/11463396/23543891/aabea3d4-fff4-11e6-9088-1eb3edb0facd.jpg)

**Comment by coptersafe** [comment]
no any difference between A and B . only firmware and hdmi board different.

B model - make USB video on FPGA processor, but A - model just transmit raw signal from traseiver to HDMI board - that all differences.

**Comment by GlovePuppet** [comment]
I can tell you the following:

P3S (and probably all the others) FC is STM32F417

P3S Gimbal has STM32F407, DSPIC32 and Artheros AR9342 

Model A RC TX has AR9342 (Running openwrt no less - I desoldered the SPI flash and dumped it). Also STM32F074 and the RF chip is Beken BK5811

When my wife gets back next weekend I will get you some high res pics of various PS main boards (also RC TX, Gimbal controller, OFDM etc). A lot of the chips numbers are obscured by the conformal coating they use and I have to remove it and squint to read the part numbers.

There's a gs_ofdm.bin file floating around people are using to unbrick their RC TX and that is targeted at  LPC17xx (they left the RTC library ASSERTS in the binary :S)

**Comment by mefistotelis** [comment]
Great; it would help me a lot to have all boards photographed.

If you're looking at the code of modules, you may use the partially recovered symbols:
https://github.com/mefistotelis/phantom-firmware-tools/tree/master/symbols

There are many symbols named for C1_FW_V01.06.0000_mi06 (which is the LPC17xx firmware).

**Comment by rylan01** [comment]
Ok, I have a few things I can photograph:
P3 Pro
OFDM Board v2
GL300A with original USB module
HDMI Module
Spare USB module after the original USB module in the GL300A stopped working after an update
P3 Advanced Camera, picked up on eBay because the original camera stopped transmitting live video after an update.
An additional P3 Pro Camera which also stopped working after an update (nice trend here.)

Willing to dismantle to get any pictures. If I dont get the camera live feed going, I am probably just going to sell all this stuff.

**Comment by GlovePuppet** [comment]
I found a few pictures of my RC TX.

GL358wA Main PCB
![gl358wa_main_pcb](https://cloud.githubusercontent.com/assets/17866734/24078582/c8a0d386-0c2e-11e7-8bce-d30ee9405ca3.png)

GL358wA BK5811 PCB
![gl358wa_bk5811_pcb](https://cloud.githubusercontent.com/assets/17866734/24078586/ce5c780c-0c2e-11e7-968c-a9a54d706ec5.png)

GL358wA WIFI Front PCB
![gl358wa_wifi_front_pcb](https://cloud.githubusercontent.com/assets/17866734/24078592/d50963ae-0c2e-11e7-9783-ccbe4db626a9.png)

GL358wA WIFI Back PCB
![gl358wa_wifi_back_pcb](https://cloud.githubusercontent.com/assets/17866734/24078593/d7db4f48-0c2e-11e7-840d-78cf02e72423.png)

**Comment by GlovePuppet** [comment]
After a little bit of time with my DMM and a P3S main board:

![p3s_std](https://cloud.githubusercontent.com/assets/17866734/24177396/7afd3646-0e5f-11e7-9d14-690328d20ae5.png)

The WiFi connector on the main PCB connects to the Gimbal PCB, there are 2 UARTs on the STM32F07 connected to the Gimbal's STM32407 and the Artheros. 

All the ESCs UART's are common-ed up and connected to the FC, I have only seen traffic being transmitted by the FC

I will provide an annotated picture and pinouts when the AV dept gets home at the weekend

**Comment by notsolowki** [comment]
Maybe someone will figure out how to recover the bootloader on the
stm32f407. Would be nice to unbrick them.

**Comment by GlovePuppet** [comment]
That's one of my goals - see my Hackaday blog for a dissection of the Naza M/P2V+

https://hackaday.io/project/19995-hacking-dji-naza-m/log/53751-big-dump

**Comment by notsolowki** [comment]
great job. i have 2 gimbals that i bricked by trying to flash the encrypted module to the stm32f407. someone on here mentioned that the bootloader from the stm32f407 could not be recovered. but i think your on the right path to decrypting everything.

**Comment by GlovePuppet** [comment]
My P3A OFDM receiver (V2) just arrived. Big chips:

STM32F103 (boring)
CY7C68013 (USB uController)
Aryston AR8001 & AR8003 (Can't find any data)
2 * PA5208 (Appears to be the RC RF RX)

**Comment by GlovePuppet** [comment]
Thinking about the Naza M (and its AT88SC crypto memory) reminded me that there is a ref to an sha204p so there is likely on of these on the FC

http://www.atmel.com/Images/Atmel-8885-CryptoAuth-ATSHA204A-Datasheet.pdf

**Comment by coptersafe** [comment]
i think no way to decrypt or hack or bruteforce AT88.. need another way.
also AT88 store configuration drone file

**Comment by GlovePuppet** [comment]
You should read my "Big Dump" - link above. Here is what I learned about AT88SC in Naza M / P2V+

1) There is a secret seed that both AT88SC and Naza M share, every Naza M / P2V+ has a different seed
2) DJI try to hide the seed in the bootloader
3) DJI screwed up implementation (Atmel say use 8 byte nonce but DJI use 8 * 0). Maybe this makes a 'hack' much easier but who cares? Dump the bootloader, get the seed ;)
4) All (including serial number, device type and license key) config data is stored in AT88SC

I think there is an Atmel ATSHA204(A) in the P3

**Comment by coptersafe** [comment]
hhmm.. sorry. seems i mistaked. later i make photo P3 FC - they use STM32F27 proc as main FC proccessor

**Comment by GlovePuppet** [comment]
My samples use ST32F417 as FC, ST32F407 in Gimbal base, ST32F072 for RC receiver. I have OFDM RX that uses ST32F103 instead (I think older version uses Nuvoton M051 based on reversing binary)

**Comment by GlovePuppet** [comment]
OFDM V2 top
![ofdm_v2_top](https://cloud.githubusercontent.com/assets/17866734/24328537/ed865bea-11a0-11e7-965f-f98488a81b83.png)

OFDM V2 bottom
![ofdm_v2_bot](https://cloud.githubusercontent.com/assets/17866734/24328540/f838256e-11a0-11e7-98af-7f2ce6879574.png)

P3S Gimbal top
![p3s_gim_top](https://cloud.githubusercontent.com/assets/17866734/24328544/19bf311e-11a1-11e7-9e80-f33b0feabc63.png)

P3S Gimbal bottom
![p3s_gim_bot](https://cloud.githubusercontent.com/assets/17866734/24328546/24a6a2d8-11a1-11e7-91b8-3bdc0af87ebc.png)

P3S Main top
![p3s_top](https://cloud.githubusercontent.com/assets/17866734/24328547/3112004e-11a1-11e7-88a2-97f74971e293.png)

P3S Main bottom
![p3s_bot](https://cloud.githubusercontent.com/assets/17866734/24328550/380d7b94-11a1-11e7-96d4-0f5a7b3c0e21.png)

P3A/P Main top
![p3ap_top](https://cloud.githubusercontent.com/assets/17866734/24328552/41de6480-11a1-11e7-9aff-8b329445ba5f.png)

P3A/P Main bottom
![p3ap_bot](https://cloud.githubusercontent.com/assets/17866734/24328556/495a1fba-11a1-11e7-83b5-b8f30206be71.png)

**Comment by mefistotelis** [comment]
Thank you @GlovePuppet.

The hardware database is slowly taking shape:
https://github.com/mefistotelis/phantom-firmware-tools/wiki/DJI-Hardware
But there are still a few photos missing - if anyone can make a better quality photo than those currently on the wiki, or has an unobfuscated version of any usually painted chip - please share.

@rylan01, from your list I'm especially waiting for the OFDM v2 and GL300a main board.

**Comment by GlovePuppet** [comment]
No problem, I will try and find some time to annotate some of the pictures with IC part numbers. I think I listed most of the major ICs on the boards I have above

**Comment by mefistotelis** [comment]
I finished sharpening all the relevant photos I had; the wiki now contains info on all P3X, P3S and P3C boards.

If anyone has an additional photo, it is a good time to share.
I'm especially interested in:
- Flight controller (MC) photo with chip markings visible
- GL300(a/b/c) main board photo with main chip (Altera/Lattice(?)) markings visible
- VPS module chip markings
Less important but still missing markings:
- Gimbal pitch/roll control chip
- The compass chip
- older version of OFDM module (v1) main chip

Also, if you have more information on a specific board (ie. list of components, or service pins descriptions), please either make an issue with update request, or clone the wiki repository and prepare a patch.

**Comment by GlovePuppet** [comment]
About the wiki: I would spend some time to document the FC commands so far. Do you want a patch or is this a possible approach:

http://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github#11481887

**Comment by mefistotelis** [comment]
I would accept both ways. Do what is preferable to you.

We definitely need such "communication protocol" wiki, for all available serial interfaces.

**Comment by mefistotelis** [comment]
Hey @notsolowki, are the pictures of RC board which you posted from GL300c? They does not show signs of BGA chip on the other side, so the board you posted definitely uses Artosyn SDR instead of FPGA.

**Comment by notsolowki** [comment]
Yes they are from the gl300c, is that a good thing?

**Comment by mefistotelis** [comment]
I marked it as GL300b for some reason, and got baffled after I was able to recognize any board by just looking at it. Thanks for clarification.

**Comment by MrBurnsAT** [comment]
Here are photos of an non working HDMI Board from an GL658B Inspire Remote.
I replaced the HDMI Board with an new one. Now RC is back to Live.

I think it has the NAND problem.

Board is labelled "WM610_GRCP_MFI368_V1"

Second Board is an "WM610_GRCP_INTERFACE_V3"

![20170703_192224](https://user-images.githubusercontent.com/24981264/27803155-5e1adfd6-6028-11e7-8e95-d1f3faccbfdf.jpg)
![20170703_192242](https://user-images.githubusercontent.com/24981264/27803171-751ad6c8-6028-11e7-84b3-26f21d5998e5.jpg)
![20170703_192338](https://user-images.githubusercontent.com/24981264/27803190-88e589e6-6028-11e7-9f8d-16e6a16367e6.jpg)
![20170703_192426](https://user-images.githubusercontent.com/24981264/27803204-981534fc-6028-11e7-9ee9-7a8170657d96.jpg)

**Comment by mefistotelis** [comment]
Thank you @MrBurnsAT.

In the meantime I scrubbed resin and photographed by OFDMv1 board and gimbal roll driver. Also, @pawelski sent me his GL300b main board photos.

So we mostly miss VPS board info; but GL300a main board photo would also help, and we don't know the compass chip markings.

**Comment by coptersafe** [comment]
compass is hmc5883l

**Comment by mefistotelis** [comment]
> compass is hmc5883l

Updated [wiki](https://github.com/mefistotelis/phantom-firmware-tools/wiki/P3-Compass-board).

**Comment by MrBurnsAT** [comment]
Like i sayed

Hooked up serial adapter
Here is what i get:


DM36x initialization passed!
UBL Product Vesion : DJI-GRC-SUPER-UBL-1.0-rc0(2014-09-19)
Dji UBL Version: 1.51(Sep 19 2014 - 16:13:09)
Booting Catalog Boot Loader
BootMode = NAND
Starting NAND Copy...
Valid magicnum, 0xA1ACED66, found in block 0x00000019.
Valid magicnum, 0xA1ACED66, found in block 0x0000001D.
No valid boot image found!
NAND Boot failed.
Aborting...

Do we have Firmware files for this?
Can we extract uboot image?
Maybe like lightbirdge hack

**Comment by mefistotelis** [comment]
> MrBurnsAT: Like i sayed...

This doesn't seem related to photos. Please move the questions to proper thread.

**Comment by MrBurnsAT** [comment]
Sorry na fault! Ill Open a New issue

**Comment by MrBurnsAT** [comment]
Found some interesting Pics on
http://www.sb-dji.com/?p=20637

From LB2 RC (GL658) with SDI Out board

I think that could be the board for m1301 Module

![014](https://user-images.githubusercontent.com/24981264/27989767-6d502486-6440-11e7-822f-60101df971cf.jpg)

![015](https://user-images.githubusercontent.com/24981264/27989770-7cc42516-6440-11e7-9098-737ee3488a55.jpg)

**Comment by MrBurnsAT** [comment]
So Now i brought a SDI Module 

![screenshot_20170709-172635](https://user-images.githubusercontent.com/24981264/27995395-f599ffa0-64cd-11e7-8c35-416814bd4fa3.png)

Have to wait some days for arrive. 

Fotos will come as fast as i can

**Comment by MrBurnsAT** [comment]
Next interesting Thing i found!

Channel Expansion Kit 
https://m.dji.com/de/product/matrice-600-series-remote-controller-channel-expansion-kit

Look at the Fotos!
Looks like an Standard HDMI Module where the extra switches are connected via CAN Bus

**Comment by danieltroger** [comment]
This isn't phantom 3 pro/adv but phantom 3 standard, but I've got two "proposals"to  these [three](https://github.com/mefistotelis/phantom-firmware-tools/wiki/WM321-Gimbal-top-board) [wiki](https://github.com/mefistotelis/phantom-firmware-tools/wiki/WM321-Camera-encoder-board) [pages](https://github.com/mefistotelis/phantom-firmware-tools/wiki/WM321-Camera-sensor-board) (@mefistotelis):

1. On the wiki it says: "The top gimbal board is responsible for **processing**, **encoding** and transmitting video for live FPV feed. It also controls the gimbal.": Are you sure? Isn't the reason that the p3 standard only does 2.7k just that, that the Ambarella SoC has to encode the live feed *and* what is being recorded to the sd card simultaneously, and therefore only can do 2.7k to the sd card? Another hint would be that you [get the encoded h264 stream from 192.168.1.3](https://github.com/hardening/Cave/blob/master/phantom3-video.cpp) which clearly is the Ambarella SoC on the camera encoder board.
2. When I recently (last friday) recieved my p3s from DJI's repair department (they got it to replace the gimbal top board) the focus was bad, so I opened the camera housing to adjust the screws. I thought the Amba SoC looked new. Then, one screw on the sensor board was impossible to open. I damaged some resistors around it
![pic of camera housing and sensor board with broken screw](https://user-images.githubusercontent.com/4047180/28927528-133bb58e-786b-11e7-9630-3ede87493b20.jpg)
So I thought I'd replace the camera housing + sensor board with another one I had laying around. I switched it on, but it kept saying "SD Card error". Then I noticed both boards in the camera housing where different and a new revision.
So here are some pictures of the camera encoder board, the sensor board is impossible to get out due to a broken screw :/
It's mainly a new (?) Amba SoC (A9SE) with different flash + ram. Also, the root user on telnet 192.168.1.3 is no longer password protected.

Angled view so you can read:
![_mg_2543](https://user-images.githubusercontent.com/4047180/28927658-6cdb3ed4-786b-11e7-987e-0edc0e714187.jpg)

Crappy pics from a vertical POV:
![_mg_2579](https://user-images.githubusercontent.com/4047180/28927769-adf9b710-786b-11e7-867d-96e58a12e705.jpg)
![_mg_2580](https://user-images.githubusercontent.com/4047180/28927770-adfbcf82-786b-11e7-907e-94a62661b53a.jpg)

Probably the gimbal top board is differen, too. But if nobody is interested in pics I don't wanna open it at the mo., 'cause it works.

**Comment by MrBurnsAT** [comment]
I would try to drill of the head of the screw.

Than u should be able to get the board out of the housing. Most times there should be a little rest of the screw that u can turn it out witch calipers

If u have a second board, measure the 2 resistors on this which now are off at the new board and replace them.

**Comment by MrBurnsAT** [comment]
PS Gimbal top Board of Pro should have a TI DaVinci DM368 for encoding which Standard Top Board should not have!

**Comment by mefistotelis** [comment]
Thank you @danieltroger.

And you're right, the top board in Standard gets the signal already compressed/encoded, it just sends it via Wi-Fi.

**Comment by danieltroger** [comment]
Those are capacitors? Uh, ok.
Yeah, I probably could take some off another board, but those resistors are a bit small to solder with my normal iron.
Oddly enough, everything still works. The gimbal only "goes crazy" when you switch it on (puts the camera in some random position after the initialization), but if I leave the drone for a minute it slowly goes back to the normal position and works fine in the air, so I'm going to leave it like this.
Can you add the pictures to the wiki, @mefistotelis ? I don't know how to fork a wiki so it'd be easier. Also, though I bet you already know it, here there are some fantastic pictures of the p3s's internals, if you need some good ones: https://www.scotttorborg.com/dji-phantom-3-standard-teardown

@MrBurnsAT yeah, I'll do that as soon as I get my hands on a good drill, thanks for the advice.

**Comment by mefistotelis** [comment]
> here there are some fantastic pictures of the p3s's internals, if you need some good ones: https://www.scotttorborg.com/dji-phantom-3-standard-teardown

Yes, I already used these.

If you have enough determination, you could also help by reading markings on each chip from the photos and writing them as text; that would make it easier to prepare the "parts" chapter on the wiki.

**Comment by MrBurnsAT** [comment]
do u still need photos?

teared down a crashed P3P without gimal
can make ever thing with this

**Comment by MrBurnsAT** [comment]
here 2 snapshots with crapy lighting

![p1140171](https://user-images.githubusercontent.com/24981264/32409953-a844913e-c1b6-11e7-9e34-19eb19e90cbb.JPG)

![p1140172](https://user-images.githubusercontent.com/24981264/32409954-a90700a2-c1b6-11e7-9d3f-b1eb8cfe9722.JPG)

**Comment by mefistotelis** [comment]
I'm definitely missing VPS module, and GL300 main board.

Can you scrub the resin from VPS chips? I'm usually doing it with a blade taken out of segment knife.
Requires time and precision, but is doable. If you're not willing to risk damaging your boards, just make photos as they are.

**Comment by MrBurnsAT** [comment]
![p1140179](https://user-images.githubusercontent.com/24981264/32410223-cbdd2340-c1bb-11e7-8905-ac2eddc03d3e.JPG)

**Comment by MrBurnsAT** [comment]
ok vps module comes take a moment

**Comment by MrBurnsAT** [comment]
pls

![p1140181](https://user-images.githubusercontent.com/24981264/32410336-dd066896-c1bd-11e7-8a37-90e9f1d347e8.JPG)

![p1140184](https://user-images.githubusercontent.com/24981264/32410337-dd2b38b0-c1bd-11e7-9606-7ecbbfcd20d3.JPG)

![p1140186](https://user-images.githubusercontent.com/24981264/32410338-dd4d92de-c1bd-11e7-9865-bc1a18382cb1.JPG)

![p1140188](https://user-images.githubusercontent.com/24981264/32410339-dd7390d8-c1bd-11e7-8771-f892c3812f30.JPG)

![p1140193](https://user-images.githubusercontent.com/24981264/32410340-ddab06f8-c1bd-11e7-82b7-b32831c56688.JPG)

**Comment by MrBurnsAT** [comment]
![p1140199](https://user-images.githubusercontent.com/24981264/32410541-ff16f73e-c1c2-11e7-9e22-b773f4d577dc.JPG)

![p1140201](https://user-images.githubusercontent.com/24981264/32410542-ff4a4f30-c1c2-11e7-80eb-2865e2a156d0.JPG)

**Comment by MrBurnsAT** [comment]
![p1140203](https://user-images.githubusercontent.com/24981264/32410631-aa4f070c-c1c5-11e7-92dd-b39b5c9dfe57.JPG)

![p1140205](https://user-images.githubusercontent.com/24981264/32410632-aa728664-c1c5-11e7-861c-74ad10bebec4.JPG)

![p1140206](https://user-images.githubusercontent.com/24981264/32410633-aa93f740-c1c5-11e7-89bc-c7fbbe5bc4b1.JPG)

![p1140208](https://user-images.githubusercontent.com/24981264/32410634-aab6daf8-c1c5-11e7-9d57-6b706ab29656.JPG)

**Comment by MrBurnsAT** [comment]
![p1140210](https://user-images.githubusercontent.com/24981264/32410756-98502f88-c1c8-11e7-806e-cd9a21c3bc5d.JPG)

![p1140211](https://user-images.githubusercontent.com/24981264/32410757-9874dd06-c1c8-11e7-89d7-bce29f28f689.JPG)

![p1140213](https://user-images.githubusercontent.com/24981264/32410758-9899d246-c1c8-11e7-8aaf-3b272c18e231.JPG)

**Comment by mefistotelis** [comment]
VPS wiki updated; thank you. I will use that IMU image too, sooner or later.

**Comment by noiseBOY** [comment]
Hi.I want to communicate with the board.
please guide me.
And what's the output of the board?

**Comment by noiseBOY** [comment]
Hi.I want to communicate with the board vps phantom(dji).
please guide me.
And what's the output of the board?

**Comment by mefistotelis** [comment]
> I want to communicate with the board vps phantom(dji). please guide me.

Get USB-to-TTL, solder to service pads which look like a serial interface and go with it. When you have any findings, please report them so we can update the wiki. You can create a separate issue for your progress and related questions.

**Comment by noiseBOY** [comment]
TNX
Do you know what the serial conection is?

2018-05-17 17:56 GMT+04:30 mefistotelis <notifications@github.com>:

**Comment by mefistotelis** [comment]
> Do you know what the serial conection is?
https://en.wikipedia.org/wiki/Serial_port
https://en.wikipedia.org/wiki/Universal_asynchronous_receiver-transmitter

**Comment by noiseBOY** [comment]
mrc
I thought it might be i2c

2018-05-17 18:07 GMT+04:30 mefistotelis <notifications@github.com>:

**Comment by mefistotelis** [comment]
The protocols used are CAN and UART. For debug interfaces, UART only.

**Comment by noiseBOY** [comment]
Thanks for the guidance

2018-05-17 18:17 GMT+04:30 mefistotelis <notifications@github.com>:

**Comment by kramer123** [comment]
Hi, I am trying to re-flow the top gimbal boards I have that have no image.  It would help me  if I knew what each chip did and which chips were ram for what.  so far one board seems better , has an image (image would come and go).  I have many drones here can upload any image that is missing here.

**Comment by mefistotelis** [comment]
> would help me if I knew what each chip did and which chips were ram for what

Everything is already on the wiki:
https://github.com/o-gs/dji-firmware-tools/wiki/WM320-Gimbal-top-board#parts
Chips are also grouped here:
https://github.com/o-gs/dji-firmware-tools/wiki/WM320-Gimbal-top-board#programming

> I have many drones here can upload any image that is missing here.

If there's any DJI board you have which has no wiki page yet or wiki page has no images, please send me the photos and I will add them.

List of all boards on the wiki is here:
https://github.com/o-gs/dji-firmware-tools/wiki/DJI-Hardware

**Comment by mefistotelis** [comment]
All Ph3 photos are now on the wiki, so closing.
