### ISSUE TITLE
WM240 Board Schematics

### ISSUE THREAD

**Issue by jergling** [o-gs/dji-firmware-tools#236]
Hi there, I bought a load of nonworking Mavic 2 batteries for reversing, and there seems to be a common failure either in the power button (a short to ground or burnt pullup resistor) and in the control transistors for the main power FETs. How can I contribute pinouts to the wiki to help people diagnose? 
Ribbon cable:
| Pin | Label | Function |
| --- | --- | --- | 
| 1 | GND | Ground |
| 2 | B_I | Safety Switch In |
| 3 | B_O | Safety Switch Out |
| 4 | BL_0 | LED ctrl 0 |
| 5 | BL_1 | LED ctrl 1 |
| 6 | BL_2 | LED ctrl 2 |
| 7 | KEY | Main Power button (pulled high by default) | 
| 8 | GND | Ground |

**Comment by mefistotelis** [comment]
You can use `git` to clone the wiki, and prepare patches for the files this way.

Or you can just post the info, like you did with the pinout - and I will update the wiki page.

Thanks for the data.
