### ISSUE TITLE
BQ30Z55 Firmware Required

### ISSUE THREAD

**Issue by bra1nslayer** [o-gs/dji-firmware-tools#278]
Hi,

I have ordered some BQ30Z55 chips from aliexpress and they came in blank. Does anyone have BQ30Z55 firmware? (*.senc file) I have EV2300/2400 and BQEVSW software for it. When i tried to detect it identifies 1717_17_17.

Thanks in advance.

**Comment by mefistotelis** [comment]
Some Ph3 firmwares have two battery modules - m1100 and m1101. Not sure if they're for different versions of the uC, or one is for the uC and the second for the BMS.
Definitely they're not encrypted though, so no 'senc' format.
