### ISSUE TITLE
Battery reset pointer appreciated

### ISSUE THREAD

**Issue by nc1914** [o-gs/dji-firmware-tools#298]
Hi. I’ve followed the excellent youtube video using a PI to access i2c, and reset the low battery flags CUDEP and CUV, which has resulted in PF=0, resealed my (Mavic Pro) battery - but it still acts like it’s dead. 
I have no leds, no response to the switch or the charger. 
Have I missed a flag please?
It’s charged to 11.5v now, had gone rather low in storage…
Many thanks for your help,
Nathan.

**Comment by mefistotelis** [comment]
No idea.
The documentation of BQ30Z55 is available, with that and the ability to read status of the chip it is possible to figure out what was tripped.
Closing.

**Comment by nc1914** [comment]
Hi, thanks for your reply, eventually I found out that holding the power button down for 30 seconds reset the bus and the battery is now working normally again.NathanOn 9 Jan 2023, at 13:33, mefistotelis ***@***.***> wrote:﻿
No idea.
The documentation of BQ30Z55 is available, with that and the ability to read status of the chip it is possible to figure out what was tripped.
Closing.

**Comment by cesaralcaide** [comment]
Hi nc194: "and reset the low battery flags CUDEP and CUV", how did yout did it?, I can't find it in the video
