### ISSUE TITLE
air2 battery bms circuit

### ISSUE THREAD

**Issue by donchapri** [o-gs/dji-firmware-tools#308]
air2 battery bms circuit i need because i charge 3.9v but can't connect with CP2112 
![20221204_113645](https://user-images.githubusercontent.com/118190181/205476833-51bf6d9e-e186-4e70-98d7-06091dbceb83.jpg)
![20221204_124323](https://user-images.githubusercontent.com/118190181/205476835-25860e75-bdd4-4056-b9e8-247fcd450421.jpg)
![20221204_124332](https://user-images.githubusercontent.com/118190181/205476837-cb85f883-791a-4069-a848-e677456d364b.jpg)

**Comment by mefistotelis** [comment]
Thanks for the photos, updated the wiki. Pity there's only one side.
https://github.com/o-gs/dji-firmware-tools/wiki/WM231-Battery-Intelligent-Board

Anyway for buy/sell requests, there are other forums. Closing.
