### ISSUE TITLE
FX2LP Battery PF clear Tool

### ISSUE THREAD

**Issue by jamesbit** [o-gs/dji-firmware-tools#309]
Hi.

What tools can I use to clear the Permanent Failure Flag of a Mavic Pro battery and FX2LP board ?

Thank you.

**Comment by mefistotelis** [comment]
No idea.
You can always implement the support of that board into `comm_sbs_bqctrl.py`. It does support the Mavic 1 battery already, so only needs implementation on the SMB transport side.

But in that case, you can create a separate issue for the implementation. Closing.
