### ISSUE TITLE
about dji_imah_fwsig.py

### ISSUE THREAD

**Issue by adamsegevgal** [o-gs/dji-firmware-tools#313]
how to start the code in the python terminal? i looked at the explanation on the readme file attached to it, but it did not seem to work.
this what i tried in the python terminal:
C:\Users\ktbm\dji_imah_fwsig.py -vv -k PRAK-2019-09 -u -i C:\Users\ktbm\Matrice_30_RC_01.02.03.42\rm700_0600_v10.06.00.33_20221108.pro.fw.sig

**Comment by mefistotelis** [comment]
Windows shell doesn't support shebang.
