### ISSUE TITLE
need to downgrade firmware on matrice 300

### ISSUE THREAD

**Issue by DeadMoroZzZz** [o-gs/dji-firmware-tools#319]
Matrice 300rtk fw 04.00.0300 and I need 03.000101.  im ready to pay for help.

**Comment by mixeysan** [comment]
> Matrice 300rtk fw 04.00.0300 and I need 03.000101.  im ready to pay for help. 

Do you think someone here will help you a rashist after what the rashists are doing in Ukraine?

**Comment by 8orms** [comment]
> > Matrice 300rtk fw 04.00.0300 and I need 03.000101.  im ready to pay for help.
> 
> Do you think someone here will help you a rashist after what the rashists are doing in Ukraine?

I think a lot of people are coming to help Russians fight the fascists (not the people) in Ukraine.
And yes, you can downgrade to 03.00101

**Comment by varfaw6-coder** [comment]
anyone can help for give the 03.00101  firmware of M300 rtk
