### ISSUE TITLE
Mavic Air 2 Anti Rollback fix 

### ISSUE THREAD

**Issue by HarP0wer** [o-gs/dji-firmware-tools#320]
Can anti rollback be canceled, is it possible to downgrade with these codes?

**Comment by aytacengin** [comment]
Depend of version number for Antirollback Value. For example, if ARB4, you can downgrade to ARB4 versions.

**Comment by HarP0wer** [comment]
Is it possible to completely delete the software and install the first version? I know the ARB values, I've been working on this for a long time
