### ISSUE TITLE
DJI Mavic (WM220) Part P01786.12 (Board Pitch Motor)

### ISSUE THREAD

**Issue by rsrmdp** [o-gs/dji-firmware-tools#345]
DJI Mavic (WM220) Part P01786.12 (Board Pitch Motor)

MP6536 Datasheet
https://html.alldatasheet.com/html-pdf/1047753/MPS/MP6536/673/10/MP6536.html

![1](https://user-images.githubusercontent.com/37049504/231177149-4a6220f7-89b3-4ed5-a7c7-8dac5978fcac.JPG)
![2](https://user-images.githubusercontent.com/37049504/231177198-b49c963d-430c-4890-a446-ec3eafe3f53a.JPG)

**Comment by mefistotelis** [comment]
Added:
https://github.com/o-gs/dji-firmware-tools/wiki/WM220-Gimbal-Pitch-Motor-board

Thanks.
