### ISSUE TITLE
Mavic 2 Zoom (WM240) Gimbal Calibration

### ISSUE THREAD

**Issue by UVTRyan** [o-gs/dji-firmware-tools#346]
When trying to run the following command:
python3 comm_og_service_tool.py WM240 --port com16 GimbalCalib
I get the error:
Error: 'NoneType' object has no attribute 'upper'

I'm running Windows 10 and I have verified I am using the correct port.
Any assistance would be appreciated.

**Comment by mefistotelis** [comment]
Fixed by:
[comm_og_service_tool: Required args are required](https://github.com/o-gs/dji-firmware-tools/commit/133860eb085eab11965d9fdf03cee753104d4896)

**Comment by UVTRyan** [comment]
@mefistotelis, perfect, I am getting a verbose error now that allows me to move forward.
Thank you for the assistance!
