### ISSUE TITLE
comm_og_service_tool.py Required Arguments

### ISSUE THREAD

**Issue by UVTRyan** [o-gs/dji-firmware-tools#349]
When running "python3 comm_og_service_tool.py WM240 --port com16 GimbalCalib", I get a verbose error saying a sub-command is required, but when running CameraCalib or FlycParam, we get the same error seen in issue #346.

Possible fix:
Add "required=True," to the end of lines 1641 and 1693.

Hopefully, this is the right channel to suggest this change, I just want to contribute in the small way that I can.

**Comment by mefistotelis** [comment]
Took me some time, but added:
[comm_og_service_tool: Avoid non-intuitive comm...](https://github.com/o-gs/dji-firmware-tools/commit/061264964df82eea8088b14014f045385e59a27b)
