### ISSUE TITLE
Mini 2 SE gimbal stuck

### ISSUE THREAD

**Issue by comsma** [o-gs/dji-firmware-tools#360]
I have a Mini 2 SE that throws the codes 40002(Gimbal Stuck) and 40011(Gimbal Calibration Error). I replaced damaged ptz cable and the flex cable and was able to issue the `JointCoarse` command but `LinearHall` issues In the terminal with no errors but the gimbal does not move.

**Comment by ardio-sos** [comment]
We're you able to finally resolve this issue?
