### ISSUE TITLE
What RTOS?

### ISSUE THREAD

**Issue by joelreymont** [o-gs/dji-firmware-tools#363]
What is the RTOS that’s used by DJI, e.g. for the flight controller? It doesn’t look like FreeRTOS to me.

**Comment by mefistotelis** [comment]
Depends.
Some info on wiki:
https://github.com/o-gs/dji-firmware-tools/wiki/Firmware-m0306

**Comment by joelreymont** [comment]
M3, M3E/T, e.g. WM265.
