### ISSUE TITLE
In Wiki section Mavic 2 Pro coreboard 2.4Ghz Amp name mentioned is wrong

### ISSUE THREAD

**Issue by akhilzid** [o-gs/dji-firmware-tools#369]
In Wiki section Mavic 2 Pro coreboard 2.4Ghz Amp name mentioned is wrong, 
Its actually "ETRA 8024" but in wiki its "FTRA 8024" please correct the info.

![M2P2 4LNA](https://github.com/o-gs/dji-firmware-tools/assets/11697407/de355bf3-c9ca-4bfc-99b0-70d35ec7f5e9)

**Comment by mefistotelis** [comment]
Done. Thanks.
