### ISSUE TITLE
Can you please guide me to how I can download the DJI Battery Killer? I have a Phantom 2 Pro with 4 brand new batteries that sat too long, any help would be incredible and greatly apprecited!

### ISSUE THREAD

**Issue by DaveSwick** [o-gs/dji-firmware-tools#394]
Also my email or number can be uploaded if needed :O)

**Comment by DaveSwick** [comment]
my email or number can be uploaded if needed :O)

**Comment by DaveSwick** [comment]
I’ve been unable to get back to you because I helping my family through hard times and I apologize but still need help lolSent from my iPhoneOn Sep 18, 2024, at 1:26 PM, mefistotelis ***@***.***> wrote:﻿
Closed #394 as completed.

**Comment by Quangtran828** [comment]
can I have the new DJIbattery killer that work with windows11 ? Thanks.....
