### ISSUE TITLE
Which is the latest version and where to download it

### ISSUE THREAD

**Issue by kpro10** [o-gs/dji-firmware-tools#401]
Hi, I want to fix my spark batteries but I don't know which is the latest version of the software and where to download it.

**Comment by kpro10** [comment]
What??? It's not completed!!!

**Comment by mefistotelis** [comment]
If you don't know how to download a git repo, we can't help you.
same about versions in version control system like git.

**Comment by kpro10** [comment]
I don't see an .exe somewhere.

**Comment by mefistotelis** [comment]
> I don't see an .exe somewhere.

The EXE to use is `python.exe`. Usage is explained in README.
