### ISSUE TITLE
DJI Phantom 4 Advanced no reply

### ISSUE THREAD

**Issue by KenwoodFox** [o-gs/dji-firmware-tools#403]
Im trying to recalibrate my hall sensors after a motor replacement but, im not getting a reply back from the drone, my model is `WM332A`

its likely not a bug with the software but any help would be appreciated! Thanks! Heres what i see on my end

```
❯ python comm_og_service_tool.py --port /dev/ttyACM0 -vv wm332 GimbalCalib LinearHall
Opened /dev/ttyACM0 at 9600

Info: The Gimbal will slowly move through all positions in all axes, several times. It will take around 30 seconds.

Prepared binary packet:
55 0e 04 66 0a 04 ce c6 20 04 08 02 ff 57
Sending packet...
Waiting for reply...
Timeout while waiting for reply.
Retrieved 54 packets (4339b), dropped 0 fragments (0b)
Prepared binary packet:
55 0e 04 66 0a 04 ce c6 20 04 08 02 ff 57
Sending packet...
Waiting for reply...
Timeout while waiting for reply.
Retrieved 61 packets (4739b), dropped 0 fragments (0b)
Prepared binary packet:
55 0e 04 66 0a 04 ce c6 20 04 08 02 ff 57
Sending packet...
Waiting for reply...
Timeout while waiting for reply.
Retrieved 54 packets (4350b), dropped 0 fragments (0b)
No response received.
Error: No response on calibration command LinearHall request.
```

![PXL_20240823_193221198](https://github.com/user-attachments/assets/821a8e94-d526-4d00-9a92-a5617e984603)

**Comment by mefistotelis** [comment]
The auto-calibration function was introduced in Mavic.

Ph4 had half-manual calibration, and we never developed a tool to perform it.

Can't remember but there are probably some threads about how repair workshops deal with that, try searching.

**Comment by KenwoodFox** [comment]
Oh! Yeah, i found a few threads about replacing all the magnets/swapping the motor housings. If you can buy motor housings online, surely you can calibrate them right?

Looks like its off-topic for this repo though :c sorry, thanks for the advice. I think im just going to have to live with it being cockeyed unless i can adjust all the magnets

**Comment by KenwoodFox** [comment]
Ah, looks like this was already brought up in #99 

Man, this kinda sucks.. Even if i swap the magnets around I'll never be able to center the camera exactly, what a terrible solution
