### ISSUE TITLE
Motor speed

### ISSUE THREAD

**Issue by notsolowki** [o-gs/dji-firmware-tools#53]
@mefistotelis, Have you found out how to get more rpm from the motors. The pwm parameters in flyc_params dont seem to be doing much, unless some of the other ones need tweaking too. I would like to see the phantom do atleast 55 or 60 and maybe even climb faster.?!

**Comment by mefistotelis** [comment]
No, I'm not doing any experiments in this area.

**Comment by notsolowki** [comment]
Well hopefully someone will jump on this issue. Ive been messing with flyc,_params and so far tge closest i got is 160mph in the simulator with really jacked up settings and rocking the sticks forward and backward. I ben this drone would have no problem going maybe even 80.
