### ISSUE TITLE
Emulation the firmware

### ISSUE THREAD

**Issue by chen1602** [o-gs/dji-firmware-tools#55]
Have someone ever tried to emulate any dji drone's firmware using firmadyne or any emulation tool?
I would to get assist if there is someone like that, or someone who wants to help with this stuff.

**Comment by mefistotelis** [comment]
That's an interesting idea, but definitely not a simple one.

For the gimbal alone, you'd need to simulate Ambarella (ARM CPU + DSP) + DaVinci (ARM9 based DSP) +  STM32F407 (ARM1 uC) + 3x dsPIC33 (uCs with motor drivers), not to mention additional sensors and devices connected to these.

I think simulating a single module would be an ambitious enough project.
