### ISSUE TITLE
dji_imah_fwsig.py  raise NotImplementedError('Signing not implemented.')

### ISSUE THREAD

**Issue by 20142995** [o-gs/dji-firmware-tools#83]
https://github.com/o-gs/dji-firmware-tools/blob/master/dji_imah_fwsig.py
里面的imah_sign函数末尾为什么有个raise
raise NotImplementedError('Signing not implemented.')

**Comment by mefistotelis** [comment]
Yes, that's correct.

**Comment by mefistotelis** [comment]
It is now implemented. You will now see a different error.
