### ISSUE TITLE
phantom3standard firmware 1.9.20  also  rename PMCAPPFw3.bin??

### ISSUE THREAD

**Issue by jiekchenid** [o-gs/dji-firmware-tools#89]
so  i do it all  and last jod 

phantom3standard firmware 1.9.20  

P3C_FW_V01.09.0200_m0306.bin   also  rename PMCAPPFw3.bin??

**Comment by mefistotelis** [comment]
One way of flashing m0306 is by placing it on sd-card as "PMCAPPFw3.bin".
