### ISSUE TITLE
P3 gimbal FPC connector

### ISSUE THREAD

**Issue by vakarcs** [o-gs/dji-firmware-tools#94]
I think the FPC connector on WL320/321 Gimbal top boards is an Omron XF2B-3545-31A connector. https://omronfs.omron.com/en_US/ecb/products/pdf/en-xf2b.pdf

**Comment by pawelsky** [comment]
It is not. It uses completely different latch mechanism...

**Comment by vakarcs** [comment]
I am speaking about this connector here:
![p01117_t4](https://user-images.githubusercontent.com/44778041/48012136-997bd500-e121-11e8-87cb-958e12114378.png)
And this is the Omron XF2B connector:
![image](https://user-images.githubusercontent.com/44778041/48012374-24f56600-e122-11e8-9583-faddc9001b24.png)
Both rotary backlock. Dimensions also match, to the extent of my measurement accuracy...

**Comment by pawelsky** [comment]
Oh, I see, you may be right about this one.

I thought you were talking about the one on the other side of the board.

**Comment by mefistotelis** [comment]
Great!
Added to parts list on wikis for both Gimbal top boards.
Thank you.
